LANGUAGES = {
    "한국어": {
        "btnPractice": "연습",
        "label": "문제",
        "label_2": "답",
        "btnDeleteAudios": "음성파일 전체삭제",
        "btnDeleteAudios_t": "mp3폴더에 있는 모든 음성파일들을 삭제합니다.",
        "btnDeleteNowAudio": "음성파일 1개삭제",
        "btnDeleteNowAudio_t": "현재 선택된 단어의 mp3파일만 삭제합니다.",
        "btnRecord": "녹음",
        "btnRecord_t": "녹음을 시작합니다. \n장치를 선택하고 확인을 누르면 녹음이 바로 시작됩니다. \n영상을 정지시켜두고 녹음준비를 하세요.",
        "btnMakeAudios_t": "단어장에 있는 모든 단어의 mp3 파일을 생성합니다. \n 미리 해두시면 시험에서 진행이 원활해집니다.",
        "btnMakeAudios": "음성파일 만들기",
        "btnOpenThisWordsMP3_t": "지금 선택된 단어의 MP3파일을 불러옵니다. \n 헷갈리는 부분을 반복청취해보세요.",
        "btnOpenThisWordsMP3": "지금단어 mp3열기",
        "btnAutoPlay_t": "표의 단어들을 자동으로 재생합니다. \n흘려듣기를 하고 싶다면 실행하세요.",
        "btnAutoPlay": "자동재생",
        "btnAutoPlay_stop": "자동재생 중지",
        "btnAutoPlay_stop_t": "자동재생을 중지합니다. 충분히 들으셨나요?",
        "cbbPlayType": "자동재생 방식을 지정하세요.",
        "chbToReadMeaning_t": "자동재생시 뜻도 같이 읽습니다.",
        "chbToReadMeaning": "뜻도 읽기",
        "label_13": "텀:",
        "txtAutoAudioDuration": "자동재생의 텀을 지정하세요. \n숫자만 쓰세요.",
        "label_14": "초",
        "label_3": "피치 조절",
        "txtPitchControler": "피치를 낮게 조절하면 목소리가 두꺼워지고 높게 조절하면 얇아집니다.",
        "label_4": "속도 조절",
        "txtSpeedControler": "속도를 조절하여 발음을 천천히 들어보거나 음성 시험의 난이도를 높여보세요.",
        "cbbPitchPreset": "피치와 속도값을 지정합니다.",
        "cbbLangToLearn": "배우고싶은 단어를 지정하세요.",
        "cbbLanguages": "Change to your language.",
        "btnTextTestWtoM_t": "텍스트 시험을 봅니다. \n단어를 보고 뜻을 쓰세요.",
        "btnTextTestWtoM": "시험",
        "label_5": "시험순서",
        "btnEdit_t": "단어파일을 편집합니다. \n단어를 추가하거나 제거하세요.",
        "btnEdit": "편집",
        "btnEdit2_t": "단어목록을 파일로 저장합니다. 빈칸이 없는지 확인해주세요",
        "btnEdit2": "저장",
        "label_7": "기본언어",
        "btnAudioTestWtoM_t": "음성 시험을 봅니다. \n단어를 듣고 뜻을 쓰세요.",
        "btnAudioTestWtoM": "음성시험",
        "label_6": "학습언어",
        "cbbTestType": "시험 순서를 지정해보세요. \n표 기준으로 위로 또는 아래로 또는 무작위로 시험을 진행하세요.",
        "btnAudioTestMtoW_t": "음성 시험을 봅니다.\n뜻을 듣고 단어 원어를 쓰세요.",
        "btnAudioTestMtoW": "거꾸로음성",
        "cbbBaseLang": "모국어 또는 제2 사용언어를 선택하세요.",
        "btnPractice_t": "연습모드는 표가 사라지지 않는 오픈북형식의 연습입니다. \n연습모드의 정답/오답은 정답률에 반영되지 않습니다.",
        "btnPractice": "연습",
        "btnAudioTestDictation_t": "음성 시험을 봅니다.\n원어를 듣고 원어를 쓰세요.",
        "btnAudioTestDictation": "받아쓰기",
        "btnTextTestMtoW_t": "텍스트 시험을 봅니다. \n뜻을 보고 원어를 쓰세요.",
        "btnTextTestMtoW": "거꾸로시험",
        "btn_browser_t": "현재 선택된 단어로 구글 검색을 해보세요. \n검색창이 열립니다. \n(단축키 F10)",
        "btn_browser": "현재 단어 검색",
        "btnDeleteScores_t": "번호, 단어, 뜻을 제외한 시험 결과를 전부 삭제합니다.",
        "btnDeleteScores": "기록삭제",
        "btnAlignCellsWidth_t": "표 넓이를 자동으로 정렬합니다.",
        "btnAlignCellsWidth": "표너비정렬",
        "btnAutoInputNumbers_t": "편집시 번호를 한 번에 입력합니다.",
        "btnAutoInputNumbers": "번호자동입력",
        "label_8": "단어 파일",
        "cbbWordFile": "단어파일을 고를 수 있습니다. \n휠로 빠르게 선택해보세요. \n파일을 다시 선택하려면 맨 위로 돌아가기를 누르세요.",
        "btnWordFileOpen_t": "단어파일을 불러옵니다.",
        "btnWordFileOpen": "단어파일열기",
        "btnRefreshWordList_t": "새로 추가한 파일이 있다면 이 버튼을 눌러서 파일을 목록에 추가하세요.",
        "btnRefreshWordList": "목록새로고침",
        "btnDeleteWordFile_t": "현재 선택중인 파일을 삭제합니다. \n될 수 있으면 삭제하지 말고 보관해서 나중에 또 시험을 진행해보세요.",
        "btnDeleteWordFile": "단어파일삭제",
        "btnMergeFiles_t": "여러 단어파일을 하나의 파일로 통합합니다.",
        "btnMergeFiles": "파일통합",
        "btnDivideFile_t": "단어를 분리하여 다른 파일로 저장합니다.\n단어를 복수 선택하고 버튼을 누르세요.",
        "btnDivideFile": "단어분리",
        "label_9": "시험모드",
        "chbAllWords": "모든 단어",
        "chbAllWords_t": "시험 시 모든 단어를 테스트합니다.",
        "chbOnlyIncorrects": "오답만",
        "chbOnlyIncorrects_t": "시험 시 이전 시험의 오답문제만을 테스트 합니다.",
        "chbOnlyLowRates": "정답률",
        "chbOnlyLowRates_t": "시험 시 지정한 정답률 이하의 단어만 시험을 봅니다.",
        "label_10": "이하만",
        "tbWordList0": "번호",
        "tbWordList1": "단어",
        "tbWordList2": "뜻",
        "tbWordList3": "오답비교",
        "tbWordList4": "정답횟수",
        "tbWordList5": "정답률",
        "tbWordList6": "최근소요시간",
        "tbWordList7": "최단소요시간",
        "tbWordList8": "방금시험채점",
        "tbWordList9": "마지막시험일시",
        "lbWordsCounter": "남은 갯수: N/N",
        "lbTimer": "00:00:00.000",
        "lbThreeCount": "Count",
        "label_11": "컬러테마:",
        "label_cbbLanguages": "Languages:",
        "label_12": "볼륨:",
        "label_cbbFontSetting": "글씨체",
        "label_cbbFontSetting_tolearn": "학습언어",
        "txtVolume": "볼륨값을 입력하세요.",
        "lbLastTest": "마지막시험 n일 지남",
        "cbbTheme": "지루할 때 테마를 바꿔 집중력을 올려보세요.",
        "btnPrintWords": "단어출력",
        "btnPrintWords_t": "표의 단어와 뜻을 출력합니다. \n밖에서도 단어를 확인할 수 있습니다.",
        "cbbPitchPreset_list":{
            "lowest_slow": "중저음느림",
            "lowest_normal": "중저음보통",
            "lowest_fast": "중저음빠름",
            "low_slow": "저음느림",
            "low_normal": "저음보통",
            "low_fast": "저음빠름",
            "slow": "느림",
            "normal": "보통",
            "fast": "빠름",
            "high_slow": "고음느림",
            "high_normal": "고음보통",
            "high_fast": "고음빠름",
            "random_preset": "랜덤프리셋",
            "everytime_random_preset": "매회랜덤프리셋",
            "random_pitch": "랜덤피치",
            "everytime_random_pitch": "매회랜덤피치",
            "random_speed": "랜덤속도",
            "everytime_random_speed": "매회랜덤속도",
            "random_pitch_speed": "피치속도랜덤",
            "everytime_random_pitch_speed": "매회피치속도랜덤",
            "user": "사용자지정",
        },
        "cbbTestType_list": {
            "Descending": "내림차순", 
            "Ascending": "오름차순", 
            "Random": "무작위",
        },
        "cbbPlayType_list": {
            "Descending": "내림차순", 
            "Ascending": "오름차순", 
            "Random": "무작위",
        },
        "cbbTheme_list": {
            "Default": "기본", 
            "Dark": "다크", 
            "Emerald": "에메랄드", 
            "Pink": "핑크", 
            "Evening_Sky": "저녁하늘", 
            "Campfire_Glow": "저녁모닥불", 
            "Magma": "마그마", 
            "Ice": "아이스", 
            "Space": "우주",
            "Forest": "숲속", 
            "Rainy_Day": "빗속", 
            "Desert": "사막", 
            "Choco": "초코", 
            "Navy_Admiral": "해군제독", 
            "Royal_Scenery": "왕실풍경", 
            "Clerical_Robe": "사제복", 
            "Ancient_Egypt": "고대이집트",
            "Gemstone": "보석", 
            "Go_Stones": "바둑알",
        },
        "cbbWordFile_list": {
            "no_sub_folder": "----하위폴더가 없습니다.----",
            "no_file_click_edit": "파일이 없습니다. 편집을 눌러 파일을 생성해주세요.",
            "no_recent_file": "----최근에 연 파일이 없습니다----.",
            "go_to_top": "↑↑↑맨 위로 돌아가기↑↑↑",
            "current_folder": "→→→→현재 폴더들←←←←",
            "files_in_current_folder": "↓↓↓↓현재 폴더의 파일↓↓↓↓",
            "recent_file": "★★★★최근 연 파일★★★★",
            "oldest_tested": "✏시험본 지 오래된 파일✏",
            "no_oldest_tested": "----시험 본 파일 없음----",
        },
        "Custom_QDialog_buttons": {
            "text_ok": "✅확인",
            "text_cancel": "❌취소",
            "text_cancel_t": "❌ 모든 녹음 내용을 취소하고 메모장으로 돌아갑니다.",
            "text_exit": "❌끝내기",
            "text_exit_t": "❌편집을 종료합니다.",
            "text_play": "▶️재생",
            "text_play_t": "▶️빨간선과 파란선 사이를 재생합니다. \n 재생속도 50 이하에서는 기계음처럼 들릴 수 있습니다.",
            "text_stop": "⏹️정지",
            "text_stop_t": "⏹️재생을 일시정지 합니다.",
            "text_save": "💾저장",
            "text_save_t": "💾 선택한 오디오를 저장합니다.",
            "text_delete": "🗑️삭제",
            "text_area_save": "💾선택범위저장",
            "text_area_save_t": "💾빨간선과 파란선 사이의 오디오 데이터를 저장합니다. \n녹음된 단어mp3에 덮어쓰기 하세요.",
            "text_edit": "📝편집",
            "text_edit_t": "🔧 편집 모드로 들어갑니다.",
            "text_test_done": "❌시험 마치기",
            "text_test_keep_going": "📝시험 계속",
            "text_practic_wtom": "📤단어 보고 뜻 쓰기",
            "text_practic_mtow": "📥뜻 보고 단어 쓰기",
            "text_practic_dictation": "🗣️📝받아쓰기",
            "text_edit_justexit": "❌저장하지 않고 종료",
            "text_edit_override": "💾📥덮어쓰기",
            "text_edit_save_othername": "💾다른 이름으로 저장",
            "text_edit_keep_editing": "📝편집 계속",
            "text_select": "💾선택",
            "text_test_all_word": "📝모든단어시험",
        },
        "Custom_QDialog_label_title": {
            "text_exit": "❌끝내기",
            "text_save": "💾저장",
            "text_warning": "⚠️경고",
            "text_select_device": "🛠️장치 선택",
            "text_recording_complete": "🎉녹음 완료",
            "text_aleart": "❗알림",
            "text_complete": "🎉완료",
            "text_error": "🚨오류",
            "text_result": "📊시험 결과",
            "text_select_practice_mode": "🎯연습 모드 선택",
            "text_cancel": "❌취소",
            "text_delete_file": "❌💾파일 삭제",
            "text_delete_complete": "✅삭제 완료",
            "text_audio_edit": "🎶🔧오디오 편집",
            "text_PrintOptionsDialog": "📝출력 설정",
            "text_show_device_selection_dialog": "🔧녹음 장치 선택",
        },
        "Custom_QDialog_label_content": {
            "audio_editor_start": "시작:",
            "audio_editor_current": "재생위치:",
            "audio_editor_end": "끝:",
            "audio_editor_speed_control": "속도조절",
            "audio_editor_done": "정말 끝내시겠습니까? \n 녹음한 내용이 사라집니다. \n (파일로 저장한 것은 제외)",
            "audio_editor_save_succesed": "녹음 저장 성공!",
            "audio_editor_save_failed": "녹음 저장 실패:",
            "print_choose_to_print": "인쇄할 항목을 선택하세요:",
            "print_font_size": "폰트 크기를 선택하세요:",
            "search_selected_word_no_word": "선택된 단어가 없습니다!",
            "search_selected_word_choose_word": "테이블에서 단어를 선택하세요!", #open_mp3_file_to_audio_editor_choose_word 겹침
            "show_overlay_recording": "🔴 녹음중...",
            "show_overlay_press_ESC": "ESC를 누르면 녹음 종료",
            "select_device_choose_device": "녹음할 장치를 선택해 주세요.",
            "show_edit_or_save_dialog_recording_done": "녹음이 완료되었습니다. 어떻게 처리하시겠습니까?",
            "start_auto_play_not_condition": "조건에 맞는 단어가 없습니다!",
            "handle_header_click_h": "시간", #parse_time, qtime_to_string 겹침 
            "handle_header_click_m": "분", #parse_time, qtime_to_string 겹침
            "handle_header_click_s": "초", #parse_time, qtime_to_string 겹침
            "delete_temp_files_delete_succesed": "mp3가 성공적으로 삭제되었습니다!",
            "delete_temp_files_delete_error": "파일 삭제 중 오류 발생:",
            "delete_temp_no_selection": "선택된 단어가 없습니다.",
            "delete_temp_file_not_found": "선택된 단어의 mp3가 없거나 찾을 수 없습니다.",
            "delete_temp_no_folder": "mp3 폴더가 존재하지 않습니다.",
            "show_completion_message": "모든 음성 파일이 생성되었습니다.",
            "new_time_record_check_no_record": "기록 없음", #save_previous_records, qtime_to_string 겹침
            "toggle_test_mode_no_condition": "시험 조건이 맞지 않습니다! \n모든 단어로 시험을 보시겠습니까?",
            "toggle_test_mode_surt_to_end": "지금 시험을 마치면 이번 테스트는 무효가 됩니다. \n시험을 마치시겠습니까?",
            "toggle_practice_mode_no_word": "시험 조건이 맞지 않아 문제가 생성되지 않았습니다. \n시험 조건을 확인해주세요. \n(ex: 오답이 없는데 오답만 체크됨",
            "display_result_correct_num": "맞춘 갯수:",
            "display_result_total_time": "총 시험 시간:",
            "show_feedback_label_cor": "정답!",
            "show_feedback_var_cor": "정답",
            "show_feedback_label_incor": "오답...",
            "show_feedback_var_incor": "오답", #create_word_meaning_list, get_filtered_rows 겹침
            "show_feedback_label_none": "알 수 없는 값",
            "start_test_forTest_des": "내림차순", #create_word_meaning_list 겹침
            "start_test_forTest_as": "오름차순", #create_word_meaning_list 겹침
            "start_test_forTest_rd": "무작위", #create_word_meaning_list 겹침
            "next_question_forTest_remain": "남은 문제:", #check_answer_forTest 겹침
            "next_question_forTest_start": "시작!", 
            "keyPressEvent_label": "-정답률",
            "number_checker_before_test_error1": "번호는 1 이상의 양수여야 합니다.",
            "number_checker_before_test_error2": "번호는 양의 정수여야 합니다.\n번호자동입력 버튼을 눌러 올바르게 입력하세요.",
            "number_checker_before_test_label": "단어나 뜻에 빈칸이 있습니다.\n편집으로 빈칸이 없게 해주세요.",
            "toggle_practice_mode_wtom": "⏭️단어 보고 뜻 쓰기", #show_practice_choice_dialog 겹침
            "toggle_practice_mode_mtow": "⏮️뜻 보고 단어 쓰기", #show_practice_choice_dialog 겹침
            "toggle_practice_mode_dict": "🗣️📝받아쓰기", #show_practice_choice_dialog 겹침
            "toggle_edit_mode_label": "빈 칸이 있습니다. 모든 칸을 채워주세요.",
            "load_csv_label": "CSV 파일을 읽는 중 오류가 발생했습니다:",
            "show_save_options_label": "변경 사항을 어떻게 처리하시겠습니까?",
            "save_as_new_file_dialog_title": "💾다른 이름으로 저장",
            "delete_current_file_sure_to_delete": "파일을 정말로 삭제하시겠습니까?",
            "delete_current_file_delete_done": "파일이 삭제되었습니다.",
            "delete_current_file_delete_error": "파일 삭제 중 오류가 발생했습니다:",
            "delete_current_file_delete_cancel": "파일 삭제가 취소되었습니다.",
            "delete_current_file_no_file": "삭제할 파일이 없습니다.",
            "save_changes_label": "비어있는 행이 있습니다. 모든 행을 채워주세요.",
            "on_combobox_changed_error": "파일을 찾을 수 없습니다:",
            "update_last_test_label_y": "년",
            "update_last_test_label_m": "월",
            "update_last_test_label_d": "일",
            "update_last_test_label_resisted_file": "파일등록",
            "update_last_test_label_last_test": " | 마지막시험 ",
            "update_last_test_label_d_passed": "일 지남",
            "PrintOptionsDialog_wordonly": "단어만 출력",
            "PrintOptionsDialog_meaningonly": "뜻만 출력",
            "PrintOptionsDialog_wordmeaning": "단어와 뜻 출력",
            "PrintOptionsDialog_selectcontent": "인쇄할 항목을 선택하세요:",
            "PrintOptionsDialog_fontsize": "폰트 크기를 선택하세요:",
            "show_practice_choice_dialog_select_mode": "연습 모드를 선택하세요",
            "update_last_test_label_no_file": "파일이 존재하지 않습니다.",
        },
        "table_values": {
            "correct": "정답",
            "wrong": "오답",
            "no_record": "기록 없음"
        },
        "file_merging": {
            "title": "파일 단어 통합",
            "btn_file_open": "파일가져오기",
            "btn_except_file": "파일제외",
            "btn_files_to_merge": "파일통합",
            "btn_exit": "닫기",
            "dialog_open_title": "파일선택",
            "dialog_save_title": "파일통합저장",
            "merging_completed": "파일이 성공적으로 통합되었습니다.",
            "completed": "완료",
            "merging_error": "병합 중 오류 발생:",
            "error": "오류",
            "no_file_to_merge": "병합할 파일이 없습니다.",
            "warning": "경고",
            "overwrite_warning": "저장하려는 파일이 병합 대상 중 하나입니다.\n덮어쓰시겠습니까?",
            "yes": "네(덮어쓰기)",
            "no": "아니오(다른이름으로)"
        },
        "file_divide": {
            "file_not_selected_title": "알림",
            "file_not_selected": "저장할 단어를 선택하세요.",
            "file_saving": "저장",
            "file_saved_title": "완료",
            "file_saved": "선택한 단어가 저장되었습니다.",
        },
        "jsonerror_nofile": "설정 파일이 없습니다. 기본값을 사용합니다.",
        "jsonerror_valueerror": "설정 파일 형식 오류. 기본값을 사용합니다.",
        "wordfileloaded_nofile1": "불러올 파일이 없습니다.",
        "wordfileloaded_nofile2": "편집으로 단어 목록을 작성하세요.",
        "wordfileloaded_success1": "파일이 성공적으로 불러와졌습니다.",
        "wordfileloaded_success2": "연습이나 시험을 통해 단어를 연습하세요.",
        "test_contition_error1": "시험 종료!", #tested_well1 겹침
        "test_contition_error2": "시험조건을 설정하고 다시 시험을 보세요.",
        "tested_well2": "시험 결과를 확인하고 또 연습해보세요.",
        "practicing_done1": "연습 종료!",
        "practicing_done2": "연습이 충분하다면 실전으로!",
        "is_editing1": "컨트롤+엔터: 행 추가",
        "is_editing2": "ESC로 편집 해제 후 컨트롤+백스페이스: 행 삭제",
    },
    "English": {
        "btnPractice": "Practice",
        "label": "Question",
        "label_2": "Answer",
        "btnDeleteAudios": "Delete All Audio Files",
        "btnDeleteAudios_t": "Deletes all audio files in the mp3 folder.",
        "btnDeleteNowAudio": "Delete Current One Audio",
        "btnDeleteNowAudio_t": "Deletes only the mp3 file of the currently selected word.",
        "btnRecord": "Record",
        "btnRecord_t": "It begins to record. \n It'll start to record as soon as you choose device and click OK. \n Pause video to record.",
        "btnMakeAudios_t": "It generates mp3 files from all words in the word list below. \n Your test will go well if you make mp3s.",
        "btnMakeAudios": "Generate audios",
        "btnOpenThisWordsMP3_t": "It loads mp3 file from the word you choose below. \n You can repeat to listen where you are confused.",
        "btnOpenThisWordsMP3": "Open mp3 file",
        "btnAutoPlay_t": "It'll play words automatically from the word list below. \n You can hear while you are afk.",
        "btnAutoPlay": "Autoplay",
        "btnAutoPlay_stop": "Stop autoplaying",
        "btnAutoPlay_stop_t": "Stops autoplaying, did you listen enough?",
        "cbbPlayType": "You can choose a type of autoplay",
        "chbToReadMeaning_t": "It reads meaning also",
        "chbToReadMeaning": "meaning also",
        "label_13": "Space:",
        "txtAutoAudioDuration": "Specify the interval for auto playback.\nNumbers only.",
        "label_14": "sec",
        "label_3": "pitch control",
        "txtPitchControler": "Lowering the pitch makes the voice deeper, while raising it makes the voice thinner.",
        "label_4": "speed control",
        "txtSpeedControler": "Adjust the speed to listen to the pronunciation more slowly or to increase the difficulty of the voice test.",
        "cbbPitchPreset": "Specify pitch and speed.",
        "cbbLangToLearn": "Select a language to learn.",
        "cbbLanguages": "사용자 언어를 바꾸세요.",
        "btnTextTestWtoM_t": "It's text test \n write meaning from a word.",
        "btnTextTestWtoM": "Text test",
        "label_5": "Test type",
        "btnEdit_t": "It edits word list. \n You can add or delete words",
        "btnEdit": "Edit",
        "btnEdit2_t": "Save the word list to a file. Please make sure there are no empty fields.",
        "btnEdit2": "Save",
        "label_7": "Base language",
        "btnAudioTestWtoM_t": "It's audio test. \n write meaning after listening audio.",
        "btnAudioTestWtoM": "Audio test",
        "label_6": "Language to learn",
        "cbbTestType": "Choose the test type.\nProceed with the test in ascending, descending, or random order based on the table.",
        "btnAudioTestMtoW_t": "It's audio test.\n write word after listening audio.",
        "btnAudioTestMtoW": "Audio test \n from meaning",
        "cbbBaseLang": "Choose your language.",
        "btnPractice_t": "Practice mode is an open-book style where the table remains visible.\nCorrect or incorrect answers in practice mode do not affect the accuracy rate.",
        "btnPractice": "Practice",
        "btnAudioTestDictation_t": "It's dictation.\n write word after listening word.",
        "btnAudioTestDictation": "Dictation",
        "btnTextTestMtoW_t": "It's text test \n write word from meaning.",
        "btnTextTestMtoW": "Text test \n from meaning",
        "btn_browser_t": "Search the currently selected word on Google.\nA browser window will open.\n(Shortcut key: F10)",
        "btn_browser": "Search",
        "btnDeleteScores_t": "Deletes all test results except for the number, word, and meaning.",
        "btnDeleteScores": "Delete results",
        "btnAlignCellsWidth_t": "Automatically adjust the table column widths.",
        "btnAlignCellsWidth": "Align width",
        "btnAutoInputNumbers_t": "Automatically input numbers all at once.",
        "btnAutoInputNumbers": "Input numbers",
        "label_8": "Word file",
        "cbbWordFile": "You can select a word file.\nUse the mouse wheel to scroll quickly.\nTo reselect a file, scroll back to the top.",
        "btnWordFileOpen_t": "It loads word file",
        "btnWordFileOpen": "Open word file",
        "btnRefreshWordList_t": "If you've added a new file, click this button to add it to the list.",
        "btnRefreshWordList": "Refresh file list",
        "btnDeleteWordFile_t": "Deletes the currently selected file. \n If possible, try not to delete it—keep it for future tests.",
        "btnDeleteWordFile": "Delete word file",
        "btnMergeFiles_t": "Merge multiple word files into one.",
        "btnMergeFiles": "Merge Files",
        "btnDivideFile_t": "Split words into another file.\nSelect multiple words and click the button.",
        "btnDivideFile": "Split Words",
        "label_9": "Test type",
        "chbAllWords": "All words",
        "chbAllWords_t": "You'll test all words",
        "chbOnlyIncorrects": "incorrects",
        "chbOnlyIncorrects_t": "You'll test with incorrects only",
        "chbOnlyLowRates": "Rates",
        "chbOnlyLowRates_t": "During the test, only words with an accuracy rate below the specified threshold will be included.",
        "label_10": "below",
        "tbWordList0": "Num",
        "tbWordList1": "Word",
        "tbWordList2": "Meaning",
        "tbWordList3": "Compare",
        "tbWordList4": "Correct Count",
        "tbWordList5": "Rate",
        "tbWordList6": "Recent Time Taken",
        "tbWordList7": "Shortest Time Taken",
        "tbWordList8": "Latest Test Result",
        "tbWordList9": "Last Test Date & Time",
        "lbWordsCounter": "Remaining: N/N",
        "lbTimer": "00:00:00.000",
        "lbThreeCount": "Count",
        "label_11": "Theme:",
        "label_cbbLanguages": "언어:",
        "label_12": "Volume:",
        "label_cbbFontSetting": "Font",
        "label_cbbFontSetting_tolearn": "to Learn",
        "txtVolume": "Input volume",
        "lbLastTest": "Passed n days from last test",
        "cbbTheme": "Change the theme when you're bored to boost your concentration.",
        "btnPrintWords": "Print",
        "btnPrintWords_t": "Print the words and meanings from the table.\nYou can review them even outside the program.",
        "cbbPitchPreset_list":{
            "lowest_slow": "Lowest pitch & Slow",
            "lowest_normal": "Lowest pitch & Normal",
            "lowest_fast": "Lowest pitch & Fast",
            "low_slow": "Low pitch & Slow",
            "low_normal": "Low pitch & Normal",
            "low_fast": "Low pitch & Fast",
            "slow": "Slow",
            "normal": "Normal",
            "fast": "Fast",
            "high_slow": "High pitch & Slow",
            "high_normal": "High pitch & Normal",
            "high_fast": "High pitch & Fast",
            "random_preset": "Random Preset",
            "everytime_random_preset": "Every Time Random Preset",
            "random_pitch": "Random Pitch",
            "everytime_random_pitch": "Every Time Random Pitch",
            "random_speed": "Random Speed",
            "everytime_random_speed": "Every Time Random Speed",
            "random_pitch_speed": "Random Pitch & Speed",
            "everytime_random_pitch_speed": "Every Time Random Pitch & Speed",
            "user": "User Defined"
        },
        "cbbTestType_list": {
            "Descending": "Descending", 
            "Ascending": "Ascending", 
            "Random": "Random",
        },
        "cbbPlayType_list": {
            "Descending": "Descending", 
            "Ascending": "Ascending", 
            "Random": "Random",
        },
        "cbbTheme_list": {
            "Default": "Default", 
            "Dark": "Dark", 
            "Emerald": "Emerald", 
            "Pink": "Pink", 
            "Evening_Sky": "Evening Sky", 
            "Campfire_Glow": "Campfire Glow", 
            "Magma": "Magma", 
            "Ice": "Ice", 
            "Space": "Space",
            "Forest": "Forest", 
            "Rainy_Day": "Rainy Day", 
            "Desert": "Desert", 
            "Choco": "Choco", 
            "Navy_Admiral": "Navy Admiral", 
            "Royal_Scenery": "Royal Scenery", 
            "Clerical_Robe": "Clerical Robe", 
            "Ancient_Egypt": "Ancient Egypt",
            "Gemstone": "Gemstone", 
            "Go_Stones": "Go Stones",
        },
        "cbbWordFile_list": {
            "no_sub_folder": "---- No Subfolders Available ----",
            "no_file_click_edit": "No files found. Click 'Edit' to create a file.",
            "no_recent_file": "---- No Recently Opened Files ----",
            "go_to_top": "↑↑↑ Back to Top ↑↑↑",
            "current_folder": "→→→→ Current Folders ←←←←",
            "files_in_current_folder": "↓↓↓↓ Files in Current Folder ↓↓↓↓",
            "recent_file": "★★★★ Recently Opened Files ★★★★",
            "oldest_tested": "✏ Oldest Tested File ✏",
            "no_oldest_tested": "---- No Tested File ----",
        },
        "Custom_QDialog_buttons": {
            "text_ok": "✅ OK",
            "text_cancel": "❌ Cancel",
            "text_cancel_t": "❌ Cancel all recordings and return to the wordlist.",
            "text_exit": "❌ Exit",
            "text_exit_t": "❌ Exit editing mode.",
            "text_play": "▶️ Play",
            "text_play_t": "▶️ Play the section between the red and blue lines. \n At playback speed below 50, the sound may become robotic.",
            "text_stop": "⏹️ Stop",
            "text_stop_t": "⏹️ Pause the playback.",
            "text_save": "💾 Save",
            "text_save_t": "💾 Save the selected audio.",
            "text_delete": "🗑️ Delete",
            "text_area_save": "💾 Save Selected Area",
            "text_area_save_t": "💾 Save the audio between the red and blue lines.\nOverwrite the recorded word MP3 file.",
            "text_edit": "📝 Edit",
            "text_edit_t": "🔧 Enter editing mode.",
            "text_test_done": "❌ Finish Test",
            "text_test_keep_going": "📝 Continue Test",
            "text_practic_wtom": "📤 Word to Meaning",
            "text_practic_mtow": "📥 Meaning to Word",
            "text_practic_dictation": "🗣️📝 Dictation",
            "text_edit_justexit": "❌ Exit Without Saving",
            "text_edit_override": "💾📥 Overwrite",
            "text_edit_save_othername": "💾 Save As",
            "text_edit_keep_editing": "📝 Continue Editing",
            "text_select": "💾 Select",
            "text_test_all_word": "📝 Test All Words"
        },
        "Custom_QDialog_label_title": {
            "text_exit": "❌ Exit",
            "text_save": "💾 Save",
            "text_warning": "⚠️ Warning",
            "text_select_device": "🛠️ Select Device",
            "text_recording_complete": "🎉 Recording Complete",
            "text_aleart": "❗ Alert",
            "text_complete": "🎉 Complete",
            "text_error": "🚨 Error",
            "text_result": "📊 Test Results",
            "text_select_practice_mode": "🎯 Select Practice Mode",
            "text_cancel": "❌ Cancel",
            "text_delete_file": "❌💾 Delete File",
            "text_delete_complete": "✅ Deletion Complete",
            "text_audio_edit": "🎶🔧 Audio Editing",
            "text_PrintOptionsDialog": "📝 Print Settings",
            "text_show_device_selection_dialog": "🔧 Select Recording Device"
        },
        "Custom_QDialog_label_content": {
            "audio_editor_start": "Start:",
            "audio_editor_current": "Playback Position:",
            "audio_editor_end": "End:",
            "audio_editor_speed_control": "Speed Control",
            "audio_editor_done": "Are you sure you want to exit?\nUnsaved recordings will be lost.\n(Files already saved will be kept)",
            "audio_editor_save_succesed": "Recording saved successfully!",
            "audio_editor_save_failed": "Failed to save recording:",
            "print_choose_to_print": "Select items to print:",
            "print_font_size": "Select font size:",
            "search_selected_word_no_word": "No word selected!",
            "search_selected_word_choose_word": "Please select a word from the table!",
            "show_overlay_recording": "🔴 Recording...",
            "show_overlay_press_ESC": "Press ESC to stop recording",
            "select_device_choose_device": "Please select a device for recording.",
            "show_edit_or_save_dialog_recording_done": "Recording complete. What would you like to do?",
            "start_auto_play_not_condition": "No words match the condition!",
            "handle_header_click_h": "h",
            "handle_header_click_m": "m",
            "handle_header_click_s": "s",
            "delete_temp_files_delete_succesed": "MP3 files deleted successfully!",
            "delete_temp_files_delete_error": "Error occurred while deleting files:",
            "delete_temp_no_folder": "MP3 folder does not exist.",
            "delete_temp_no_selection": "No word selected.",
            "delete_temp_file_not_found": "The mp3 file for the selected word is missing or cannot be found.",
            "show_completion_message": "All audio files have been generated.",
            "new_time_record_check_no_record": "No Record",
            "toggle_test_mode_no_condition": "Test conditions not met!\nWould you like to test all words instead?",
            "toggle_test_mode_surt_to_end": "If you end the test now, this attempt will not be counted.\nDo you want to end the test?",
            "toggle_practice_mode_no_word": "No questions generated due to unmatched test conditions.\nPlease check your settings.\n(e.g., Only wrong answers selected, but no wrong answers exist)",
            "display_result_correct_num": "Correct Answers:",
            "display_result_total_time": "Total Test Time:",
            "show_feedback_label_cor": "Correct!",
            "show_feedback_var_cor": "Correct",
            "show_feedback_label_incor": "Incorrect...",
            "show_feedback_var_incor": "Incorrect",
            "show_feedback_label_none": "Unknown Value",
            "start_test_forTest_des": "Descending", 
            "start_test_forTest_as": "Ascending", 
            "start_test_forTest_rd": "Random",
            "next_question_forTest_remain": "Remaining Questions:",
            "next_question_forTest_start": "Start!",
            "keyPressEvent_label": "-Accuracy Rate",
            "number_checker_before_test_error1": "Number must be a positive integer greater than 0.",
            "number_checker_before_test_error2": "Numbers must be positive integers.\nUse the 'Auto Input Numbers' button to input correctly.",
            "number_checker_before_test_label": "There are empty fields in the word or meaning.\nPlease fill them in through editing.",
            "toggle_practice_mode_wtom": "⏭️Word to Meaning",
            "toggle_practice_mode_mtow": "⏮️Meaning to Word",
            "toggle_practice_mode_dict": "🗣️📝Dictation",
            "toggle_edit_mode_label": "There are empty fields. Please fill in all fields.",
            "load_csv_label": "An error occurred while reading the CSV file:",
            "show_save_options_label": "How would you like to handle the changes?",
            "save_as_new_file_dialog_title": "💾 Save As",
            "delete_current_file_sure_to_delete": "Are you sure you want to delete this file?",
            "delete_current_file_delete_done": "File has been deleted.",
            "delete_current_file_delete_error": "An error occurred while deleting the file:",
            "delete_current_file_delete_cancel": "File deletion canceled.",
            "delete_current_file_no_file": "There is no file to delete.",
            "save_changes_label": "There are empty rows. Please fill in all rows.",
            "on_combobox_changed_error": "File not found:",
            "update_last_test_label_y": "Year",
            "update_last_test_label_m": "Month",
            "update_last_test_label_d": "Day",
            "update_last_test_label_resisted_file": "Registered File",
            "update_last_test_label_last_test": " | Last Test ",
            "update_last_test_label_d_passed": "days ago",
            "PrintOptionsDialog_wordonly": "Print Words Only",
            "PrintOptionsDialog_meaningonly": "Print Meanings Only",
            "PrintOptionsDialog_wordmeaning": "Print Words and Meanings",
            "PrintOptionsDialog_selectcontent": "Select items to print:",
            "PrintOptionsDialog_fontsize": "Select font size:",
            "show_practice_choice_dialog_select_mode": "Select Practice Mode",
            "update_last_test_label_no_file": "File does not exist.",
        },
        "table_values": {
            "correct": "correct",
            "wrong": "wrong",
            "no_record": "no record"
        },
        "file_merging": {
            "title": "Merge Word Files",
            "btn_file_open": "Import File",
            "btn_except_file": "Exclude File",
            "btn_files_to_merge": "Merge Files",
            "btn_exit": "Close",
            "dialog_open_title": "Select File",
            "dialog_save_title": "Save Merged File",
            "merging_completed": "Files have been successfully merged.",
            "completed": "Completed",
            "merging_error": "Error occurred during merging:",
            "error": "Error",
            "no_file_to_merge": "There are no files to merge.",
            "no_file_to_merge": "There are no files to merge.",
            "warning": "Warning",
            "overwrite_warning": "The file you're trying to save is one of the merge targets.\nDo you want to overwrite it?",
            "yes": "Yes (Overwrite)",
            "no": "No (Save As)",
            },
        "file_divide": {
            "file_not_selected_title": "Notice",
            "file_not_selected": "Please select words to save.",
            "file_saving": "Saving",
            "file_saved_title": "Done",
            "file_saved": "Selected words have been saved.",
        },
        "jsonerror_nofile": "There's no settings. It'll accept deafult settings.",
        "jsonerror_valueerror": "Settings error. It'll accept deafult settings.",
        "wordfileloaded_nofile1": "There's no file to load.",
        "wordfileloaded_nofile2": "Click To edit to make your word list.",
        "wordfileloaded_success1": "The file was loaded successfully.",
        "wordfileloaded_success2": "Practice the words through practicing or testing.",
        "test_contition_error1": "Test ended!",
        "test_contition_error2": "Please set the test conditions and try again.",
        "tested_well1": "Test Completed!",
        "tested_well2": "Check your results and keep practicing.",
        "practicing_done1": "Practice Completed!",
        "practicing_done2": "If you're ready, move on to the real test!",
        "is_editing1": "Ctrl + Enter: Add Row",
        "is_editing2": "Press ESC to exit editing, then Ctrl + Backspace: Delete Row"
        },
    "Español": {
        "btnPractice": "Práctica",
        "label": "Pregunta",
        "label_2": "Respuesta",
        "btnDeleteAudios": "Eliminar Todos los Archivos de Audio",
        "btnDeleteAudios_t": "Elimina todos los archivos de audio en la carpeta mp3.",
        "btnDeleteNowAudio": "Eliminar Audio Actual Solo Uno",
        "btnDeleteNowAudio_t": "Elimina solo el archivo mp3 de la palabra seleccionada.",
        "btnRecord": "Grabar",
        "btnRecord_t": "Comienza a grabar.\nEmpezará a grabar tan pronto como elijas el dispositivo y hagas clic en OK.\nPausa el video para grabar.",
        "btnMakeAudios_t": "Genera archivos MP3 para todas las palabras en la lista de abajo.\nTu prueba irá mejor si creas los MP3.",
        "btnMakeAudios": "Generar audios",
        "btnOpenThisWordsMP3_t": "Carga el archivo MP3 de la palabra que elijas abajo.\nPuedes repetir la escucha donde tengas dudas.",
        "btnOpenThisWordsMP3": "Abrir archivo MP3",
        "btnAutoPlay_t": "Reproducirá automáticamente las palabras de la lista.\nPuedes escuchar mientras estás ausente.",
        "btnAutoPlay": "Reproducción automática",
        "btnAutoPlay_stop": "Detener reproducción",
        "btnAutoPlay_stop_t": "Detiene la reproducción automática, ¿has escuchado lo suficiente?",
        "cbbPlayType": "Puedes elegir un tipo de reproducción automática",
        "chbToReadMeaning_t": "También leerá el significado",
        "chbToReadMeaning": "también significado",
        "label_13": "Espacio:",
        "txtAutoAudioDuration": "Especifica el intervalo de reproducción automática.\nSolo números.",
        "label_14": "seg",
        "label_3": "control de tono",
        "txtPitchControler": "Bajar el tono hace que la voz suene más grave, mientras que subirlo la hace más aguda.",
        "label_4": "control de velocidad",
        "txtSpeedControler": "Ajusta la velocidad para escuchar la pronunciación más lentamente o aumentar la dificultad de la prueba de voz.",
        "cbbPitchPreset": "Especifica el tono y la velocidad.",
        "cbbLangToLearn": "Selecciona un idioma para aprender.",
        "cbbLanguages": "사용자 언어를 바꾸세요.",
        "btnTextTestWtoM_t": "Es una prueba escrita.\nEscribe el significado a partir de una palabra.",
        "btnTextTestWtoM": "Prueba escrita",
        "label_5": "Tipo de prueba",
        "btnEdit_t": "Edita la lista de palabras.\nPuedes agregar o eliminar palabras.",
        "btnEdit": "Editar",
        "btnEdit2_t": "Guarda la lista de palabras en un archivo. Asegúrate de que no haya campos vacíos.",
        "btnEdit2": "Guardar",
        "label_7": "Idioma base",
        "btnAudioTestWtoM_t": "Es una prueba de audio.\nEscribe el significado después de escuchar el audio.",
        "btnAudioTestWtoM": "Prueba de audio",
        "label_6": "Idioma a aprender",
        "cbbTestType": "Elige el tipo de prueba.\nRealiza la prueba en orden ascendente, descendente o aleatorio según la tabla.",
        "btnAudioTestMtoW_t": "Es una prueba de audio.\nEscribe la palabra después de escuchar el audio.",
        "btnAudioTestMtoW": "Prueba de audio\n desde el significado",
        "cbbBaseLang": "Elige tu idioma.",
        "btnPractice_t": "El modo de práctica es estilo libro abierto, donde la tabla permanece visible.\nLas respuestas correctas o incorrectas en este modo no afectan el porcentaje de aciertos.",
        "btnPractice": "Práctica",
        "btnAudioTestDictation_t": "Es una dictado.\nEscribe la palabra después de escucharla.",
        "btnAudioTestDictation": "Dictado",
        "btnTextTestMtoW_t": "Es una prueba escrita.\nEscribe la palabra a partir del significado.",
        "btnTextTestMtoW": "Prueba escrita\ndesde el significado",
        "btn_browser_t": "Busca la palabra seleccionada en Google.\nSe abrirá una ventana del navegador.\n(Atajo: F10)",
        "btn_browser": "Buscar",
        "btnDeleteScores_t": "Elimina todos los resultados del examen excepto el número, la palabra y el significado.",
        "btnDeleteScores": "Eliminar resultados",
        "btnAlignCellsWidth_t": "Ajusta automáticamente el ancho de las columnas de la tabla.",
        "btnAlignCellsWidth": "Alinear ancho",
        "btnAutoInputNumbers_t": "Ingresa los números automáticamente de una vez.",
        "btnAutoInputNumbers": "Ingresar números",
        "label_8": "Archivo de palabras",
        "cbbWordFile": "Puedes seleccionar un archivo de palabras.\nUsa la rueda del ratón para desplazarte rápidamente.\nPara volver a seleccionar un archivo, ve al principio de la lista.",
        "btnWordFileOpen_t": "Carga el archivo de palabras",
        "btnWordFileOpen": "Abrir archivo",
        "btnRefreshWordList_t": "Si agregaste un nuevo archivo, haz clic en este botón para añadirlo a la lista.",
        "btnRefreshWordList": "Actualizar lista de archivos",
        "btnDeleteWordFile_t": "Elimina el archivo actualmente seleccionado. \n Si es posible, no lo elimines — guárdalo para futuros exámenes.",
        "btnDeleteWordFile": "Eliminar archivo de palabras",
        "btnMergeFiles_t": "Une varios archivos de palabras en uno solo.",
        "btnMergeFiles": "Unir archivos",
        "btnDivideFile_t": "Divide palabras y guárdalas en otro archivo.\nSelecciona varias palabras y pulsa el botón.",
        "btnDivideFile": "Dividir palabras",
        "label_9": "Tipo de prueba",
        "chbAllWords": "Todas las palabras",
        "chbAllWords_t": "Se evaluarán todas las palabras",
        "chbOnlyIncorrects": "Incorrectas",
        "chbOnlyIncorrects_t": "Se evaluarán solo las respuestas incorrectas",
        "chbOnlyLowRates": "Porcentaje bajo",
        "chbOnlyLowRates_t": "Durante la prueba, solo se incluirán palabras con una tasa de acierto inferior al umbral especificado.",
        "label_10": "por debajo de",
        "tbWordList0": "Núm",
        "tbWordList1": "Palabra",
        "tbWordList2": "Significado",
        "tbWordList3": "Comparar",
        "tbWordList4": "Aciertos",
        "tbWordList5": "Tasa",
        "tbWordList6": "Tiempo reciente",
        "tbWordList7": "Tiempo más corto",
        "tbWordList8": "Resultado reciente",
        "tbWordList9": "Fecha y hora del último examen",
        "lbWordsCounter": "Restantes: N/N",
        "lbTimer": "00:00:00.000",
        "lbThreeCount": "Cuenta",
        "label_11": "Tema:",
        "label_cbbLanguages": "Idioma:",
        "label_12": "Volumen:",
        "label_cbbFontSetting": "Fuente",
        "label_cbbFontSetting_tolearn": "de Aprendizaje",
        "txtVolume": "Volumen de entrada",
        "lbLastTest": "Han pasado n días desde la última prueba",
        "cbbTheme": "Cambia el tema cuando estés aburrido para mejorar tu concentración.",
        "btnPrintWords": "Imprimir",
        "btnPrintWords_t": "Imprime las palabras y sus significados desde la tabla.\nPuedes revisarlas incluso fuera del programa.",
        "cbbPitchPreset_list": {
            "lowest_slow": "Tono más bajo y lento",
            "lowest_normal": "Tono más bajo y normal",
            "lowest_fast": "Tono más bajo y rápido",
            "low_slow": "Tono bajo y lento",
            "low_normal": "Tono bajo y normal",
            "low_fast": "Tono bajo y rápido",
            "slow": "Lento",
            "normal": "Normal",
            "fast": "Rápido",
            "high_slow": "Tono alto y lento",
            "high_normal": "Tono alto y normal",
            "high_fast": "Tono alto y rápido",
            "random_preset": "Preajuste aleatorio",
            "everytime_random_preset": "Preajuste aleatorio cada vez",
            "random_pitch": "Tono aleatorio",
            "everytime_random_pitch": "Tono aleatorio cada vez",
            "random_speed": "Velocidad aleatoria",
            "everytime_random_speed": "Velocidad aleatoria cada vez",
            "random_pitch_speed": "Tono y velocidad aleatorios",
            "everytime_random_pitch_speed": "Tono y velocidad aleatorios cada vez",
            "user": "Definido por el usuario",
        },
        "cbbTestType_list": {
            "Descending": "Descendente",
            "Ascending": "Ascendente",
            "Random": "Aleatorio"
        },
        "cbbPlayType_list": {
            "Descending": "Descendente",
            "Ascending": "Ascendente",
            "Random": "Aleatorio"
        },
        "cbbTheme_list": {
            "Default": "Predeterminado",
            "Dark": "Oscuro",
            "Emerald": "Esmeralda",
            "Pink": "Rosa",
            "Evening_Sky": "Cielo al Atardecer",
            "Campfire_Glow": "Brillo de la Fogata",
            "Magma": "Magma",
            "Ice": "Hielo",
            "Space": "Espacio",
            "Forest": "Bosque",
            "Rainy_Day": "Día Lluvioso",
            "Desert": "Desierto",
            "Choco": "Chocolate",
            "Navy_Admiral": "Almirante Naval",
            "Royal_Scenery": "Paisaje Real",
            "Clerical_Robe": "Túnica Clerical",
            "Ancient_Egypt": "Egipto Antiguo",
            "Gemstone": "Piedra Preciosa",
            "Go_Stones": "Piedras de Go"
        },
        "cbbWordFile_list": {
            "no_sub_folder": "---- No hay subcarpetas disponibles ----",
            "no_file_click_edit": "No se encontraron archivos. Haz clic en 'Editar' para crear uno.",
            "no_recent_file": "---- No hay archivos abiertos recientemente ----",
            "go_to_top": "↑↑↑ Volver al principio ↑↑↑",
            "current_folder": "→→→→ Carpetas actuales ←←←←",
            "files_in_current_folder": "↓↓↓↓ Archivos en la carpeta actual ↓↓↓↓",
            "recent_file": "★★★★ Archivos abiertos recientemente ★★★★",
            "oldest_tested": "✏ Archivo más antiguo evaluado ✏",
            "no_oldest_tested": "---- No hay archivo evaluado ----",
        },
        "Custom_QDialog_buttons": {
            "text_ok": "✅ OK",
            "text_cancel": "❌ Cancelar",
            "text_cancel_t": "❌ Cancelar todas las grabaciones y volver a la lista de palabras.",
            "text_exit": "❌ Salir",
            "text_exit_t": "❌ Salir del modo de edición.",
            "text_play": "▶️ Reproducir",
            "text_play_t": "▶️ Reproduce la sección entre la línea roja y la azul. \n A velocidades de reproducción inferiores a 50, el sonido puede parecer robótico.",
            "text_stop": "⏹️ Detener",
            "text_stop_t": "⏹️ Pausar la reproducción.",
            "text_save": "💾 Guardar",
            "text_save_t": "💾 Guardar el audio seleccionado.",
            "text_delete": "🗑️ Eliminar",
            "text_area_save": "💾 Guardar área seleccionada",
            "text_area_save_t": "💾 Guardar el audio entre la línea roja y la azul.\nSobrescribe el archivo MP3 grabado.",
            "text_edit": "📝 Editar",
            "text_edit_t": "🔧 Entrar en el modo de edición.",
            "text_test_done": "❌ Terminar prueba",
            "text_test_keep_going": "📝 Continuar prueba",
            "text_practic_wtom": "📤 Palabra → Significado",
            "text_practic_mtow": "📥 Significado → Palabra",
            "text_practic_dictation": "🗣️📝 Dictado",
            "text_edit_justexit": "❌ Salir sin guardar",
            "text_edit_override": "💾📥 Sobrescribir",
            "text_edit_save_othername": "💾 Guardar como",
            "text_edit_keep_editing": "📝 Continuar editando",
            "text_select": "💾 Seleccionar",
            "text_test_all_word": "📝 Probar todas las palabras"
        },
        "Custom_QDialog_label_title": {
            "text_exit": "❌ Salir",
            "text_save": "💾 Guardar",
            "text_warning": "⚠️ Advertencia",
            "text_select_device": "🛠️ Seleccionar dispositivo",
            "text_recording_complete": "🎉 Grabación completada",
            "text_aleart": "❗ Alerta",
            "text_complete": "🎉 Completado",
            "text_error": "🚨 Error",
            "text_result": "📊 Resultados de la prueba",
            "text_select_practice_mode": "🎯 Seleccionar modo de práctica",
            "text_cancel": "❌ Cancelar",
            "text_delete_file": "❌💾 Eliminar archivo",
            "text_delete_complete": "✅ Eliminación completada",
            "text_audio_edit": "🎶🔧 Edición de audio",
            "text_PrintOptionsDialog": "📝 Configuración de impresión",
            "text_show_device_selection_dialog": "🔧 Seleccionar dispositivo de grabación"
        },
        "Custom_QDialog_label_content": {
            "audio_editor_start": "Inicio:",
            "audio_editor_current": "Posición de reproducción:",
            "audio_editor_end": "Fin:",
            "audio_editor_speed_control": "Control de velocidad",
            "audio_editor_done": "¿Estás seguro de que deseas salir?\nLas grabaciones no guardadas se perderán.\n(Los archivos ya guardados se conservarán)",
            "audio_editor_save_succesed": "¡Grabación guardada con éxito!",
            "audio_editor_save_failed": "Error al guardar la grabación:",
            "print_choose_to_print": "Selecciona los elementos a imprimir:",
            "print_font_size": "Selecciona el tamaño de fuente:",
            "search_selected_word_no_word": "¡Ninguna palabra seleccionada!",
            "search_selected_word_choose_word": "¡Selecciona una palabra de la tabla!",
            "show_overlay_recording": "🔴 Grabando...",
            "show_overlay_press_ESC": "Presiona ESC para detener la grabación",
            "select_device_choose_device": "Selecciona un dispositivo para grabar.",
            "show_edit_or_save_dialog_recording_done": "Grabación completada. ¿Qué te gustaría hacer?",
            "start_auto_play_not_condition": "¡Ninguna palabra coincide con la condición!",
            "handle_header_click_h": "h",
            "handle_header_click_m": "m",
            "handle_header_click_s": "s",
            "delete_temp_files_delete_succesed": "¡Los archivos MP3 se han eliminado con éxito!",
            "delete_temp_files_delete_error": "Se produjo un error al eliminar los archivos:",
            "delete_temp_no_folder": "La carpeta MP3 no existe.",
            "delete_temp_no_selection": "No se ha seleccionado ninguna palabra.",
            "delete_temp_file_not_found": "El archivo mp3 de la palabra seleccionada no existe o no se puede encontrar.",
            "show_completion_message": "Todos los archivos de audio han sido generados.",
            "new_time_record_check_no_record": "Sin registro",
            "toggle_test_mode_no_condition": "¡Las condiciones de la prueba no se cumplen!\n¿Quieres probar con todas las palabras en su lugar?",
            "toggle_test_mode_surt_to_end": "Si terminas la prueba ahora, este intento no será contado.\n¿Deseas finalizar la prueba?",
            "toggle_practice_mode_no_word": "No se generaron preguntas debido a condiciones no coincidentes.\nPor favor, revisa tu configuración.\n(p. ej., solo se seleccionaron respuestas incorrectas, pero no hay errores previos)",
            "display_result_correct_num": "Respuestas correctas:",
            "display_result_total_time": "Tiempo total de la prueba:",
            "show_feedback_label_cor": "¡Correcto!",
            "show_feedback_var_cor": "Correcto",
            "show_feedback_label_incor": "Incorrecto...",
            "show_feedback_var_incor": "Incorrecto",
            "show_feedback_label_none": "Valor desconocido",
            "start_test_forTest_des": "Descendente",
            "start_test_forTest_as": "Ascendente",
            "start_test_forTest_rd": "Aleatorio",
            "next_question_forTest_remain": "Preguntas restantes:",
            "next_question_forTest_start": "¡Comenzar!",
            "keyPressEvent_label": "-Tasa de aciertos",
            "number_checker_before_test_error1": "El número debe ser un entero positivo mayor que 0.",
            "number_checker_before_test_error2": "Los números deben ser enteros positivos.\nUsa el botón 'Ingresar números automáticamente' para hacerlo correctamente.",
            "number_checker_before_test_label": "Hay campos vacíos en la palabra o su significado.\nPor favor, complétalos desde la edición.",
            "toggle_practice_mode_wtom": "⏭️ Palabra → Significado",
            "toggle_practice_mode_mtow": "⏮️ Significado → Palabra",
            "toggle_practice_mode_dict": "🗣️📝 Dictado",
            "toggle_edit_mode_label": "Hay campos vacíos. Por favor, complétalos todos.",
            "load_csv_label": "Ocurrió un error al leer el archivo CSV:",
            "show_save_options_label": "¿Cómo deseas manejar los cambios?",
            "save_as_new_file_dialog_title": "💾 Guardar como",
            "delete_current_file_sure_to_delete": "¿Estás seguro de que deseas eliminar este archivo?",
            "delete_current_file_delete_done": "El archivo ha sido eliminado.",
            "delete_current_file_delete_error": "Se produjo un error al eliminar el archivo:",
            "delete_current_file_delete_cancel": "Eliminación del archivo cancelada.",
            "delete_current_file_no_file": "No hay ningún archivo para eliminar.",
            "save_changes_label": "Hay filas vacías. Por favor, complétalas todas.",
            "on_combobox_changed_error": "Archivo no encontrado:",
            "update_last_test_label_y": "Año",
            "update_last_test_label_m": "Mes",
            "update_last_test_label_d": "Día",
            "update_last_test_label_resisted_file": "Archivo registrado",
            "update_last_test_label_last_test": " | Última prueba ",
            "update_last_test_label_d_passed": "días atrás",
            "PrintOptionsDialog_wordonly": "Imprimir solo palabras",
            "PrintOptionsDialog_meaningonly": "Imprimir solo significados",
            "PrintOptionsDialog_wordmeaning": "Imprimir palabras y significados",
            "PrintOptionsDialog_selectcontent": "Selecciona los elementos a imprimir:",
            "PrintOptionsDialog_fontsize": "Selecciona el tamaño de fuente:",
            "show_practice_choice_dialog_select_mode": "Selecciona el modo de práctica",
            "update_last_test_label_no_file": "El archivo no existe."
        },
        "table_values": {
            "correct": "correcto",
            "wrong": "incorrecto",
            "no_record": "sin registro"
        },
        "file_merging": {
            "title": "Unir Archivos de Palabras",
            "btn_file_open": "Importar archivo",
            "btn_except_file": "Excluir archivo",
            "btn_files_to_merge": "Unir archivos",
            "btn_exit": "Cerrar",
            "dialog_open_title": "Seleccionar archivo",
            "dialog_save_title": "Guardar archivo combinado",
            "merging_completed": "Los archivos se han unido correctamente.",
            "completed": "Completado",
            "merging_error": "Error durante la unión:",
            "error": "Error",
            "no_file_to_merge": "No hay archivos para unir.",
            "no_file_to_merge": "No hay archivos para unir.",
            "warning": "Advertencia",
            "overwrite_warning": "El archivo que intentas guardar está entre los archivos a unir.\n¿Deseas sobrescribirlo?",
            "yes": "Sí (Sobrescribir)",
            "no": "No (Guardar como)",
        },
        "file_divide": {
            "file_not_selected_title": "Aviso",
            "file_not_selected": "Selecciona las palabras que deseas guardar.",
            "file_saving": "Guardando",
            "file_saved_title": "Completado",
            "file_saved": "Las palabras seleccionadas se han guardado.",
        },
        "jsonerror_nofile": "No hay configuraciones. Se usarán los valores predeterminados.",
        "jsonerror_valueerror": "Error en las configuraciones. Se usarán los valores predeterminados.",
        "wordfileloaded_nofile1": "No hay archivo para cargar.",
        "wordfileloaded_nofile2": "Haz clic en Editar para crear tu lista de palabras.",
        "wordfileloaded_success1": "El archivo se cargó con éxito.",
        "wordfileloaded_success2": "Practica las palabras mediante práctica o prueba.",
        "test_contition_error1": "¡Prueba finalizada!",
        "test_contition_error2": "Por favor, establece las condiciones de la prueba e inténtalo de nuevo.",
        "tested_well1": "¡Prueba completada!",
        "tested_well2": "Revisa tus resultados y sigue practicando.",
        "practicing_done1": "¡Práctica completada!",
        "practicing_done2": "¡Si estás listo, pasa a la prueba real!",
        "is_editing1": "Ctrl + Enter: Añadir fila",
        "is_editing2": "Presiona ESC para salir de la edición, luego Ctrl + Retroceso: Eliminar fila"
    },
    "Ελληνικά": {
        "btnPractice": "Άσκηση",
        "label": "Ερώτηση",
        "label_2": "Απάντηση",
        "btnDeleteAudios": "Διαγραφή Όλων των Αρχείων Ήχου",
        "btnDeleteAudios_t": "Διαγράφει όλα τα αρχεία ήχου στον φάκελο mp3.",
        "btnDeleteNowAudio": "Διαγραφή ενός αρχείου ήχου",
        "btnDeleteNowAudio_t": "Διαγράφει μόνο το αρχείο mp3 της επιλεγμένης λέξης.",
        "btnRecord": "Εγγραφή",
        "btnRecord_t": "Ξεκινά την εγγραφή.\nΘα ξεκινήσει μόλις επιλέξετε συσκευή και πατήσετε OK.\nΠαύση του βίντεο για εγγραφή.",
        "btnMakeAudios_t": "Δημιουργεί αρχεία MP3 από όλες τις λέξεις της παρακάτω λίστας.\nΗ δοκιμή σου θα πάει καλύτερα αν δημιουργήσεις MP3.",
        "btnMakeAudios": "Δημιουργία ήχων",
        "btnOpenThisWordsMP3_t": "Φορτώνει το αρχείο MP3 της λέξης που επιλέξατε παρακάτω.\nΜπορείς να το ακούσεις ξανά στα σημεία που δυσκολεύεσαι.",
        "btnOpenThisWordsMP3": "Άνοιγμα αρχείου MP3",
        "btnAutoPlay_t": "Θα αναπαράγει αυτόματα τις λέξεις από τη λίστα.\nΜπορείς να ακούς ακόμη και όταν είσαι μακριά.",
        "btnAutoPlay": "Αυτόματη αναπαραγωγή",
        "btnAutoPlay_stop": "Διακοπή αυτόματης αναπαραγωγής",
        "btnAutoPlay_stop_t": "Η αυτόματη αναπαραγωγή σταμάτησε, άκουσες αρκετά;",
        "cbbPlayType": "Μπορείς να επιλέξεις τύπο αυτόματης αναπαραγωγής",
        "chbToReadMeaning_t": "Θα διαβάσει και τη σημασία",
        "chbToReadMeaning": "και η σημασία",
        "label_13": "Διάστημα:",
        "txtAutoAudioDuration": "Καθόρισε το διάστημα για την αυτόματη αναπαραγωγή.\nΜόνο αριθμοί.",
        "label_14": "δευτ.",
        "label_3": "έλεγχος τόνου",
        "txtPitchControler": "Μειώνοντας τον τόνο, η φωνή γίνεται πιο βαθιά, ενώ αυξάνοντάς τον γίνεται πιο λεπτή.",
        "label_4": "έλεγχος ταχύτητας",
        "txtSpeedControler": "Ρύθμισε την ταχύτητα για να ακούσεις την προφορά πιο αργά ή για να αυξήσεις τη δυσκολία της φωνητικής δοκιμής.",
        "cbbPitchPreset": "Καθόρισε τόνο και ταχύτητα.",
        "cbbLangToLearn": "Επέλεξε μια γλώσσα για εκμάθηση.",
        "cbbLanguages": "사용자 언어를 바꾸세요.",
        "btnTextTestWtoM_t": "Είναι δοκιμή κειμένου\nγράψε τη σημασία από τη λέξη.",
        "btnTextTestWtoM": "Δοκιμή κειμένου",
        "label_5": "Τύπος δοκιμής",
        "btnEdit_t": "Επεξεργάζεται τη λίστα λέξεων.\nΜπορείς να προσθέσεις ή να διαγράψεις λέξεις.",
        "btnEdit": "Επεξεργασία",
        "btnEdit2_t": "Αποθήκευσε τη λίστα λέξεων σε αρχείο. Βεβαιώσου ότι δεν υπάρχουν κενά πεδία.",
        "btnEdit2": "Αποθήκευση",
        "label_7": "Βασική γλώσσα",
        "btnAudioTestWtoM_t": "Είναι φωνητική δοκιμή.\nΓράψε τη σημασία αφού ακούσεις τον ήχο.",
        "btnAudioTestWtoM": "Φωνητική δοκιμή",
        "label_6": "Γλώσσα προς εκμάθηση",
        "cbbTestType": "Επέλεξε τύπο δοκιμής.\nΚάνε τη δοκιμή με αύξουσα, φθίνουσα ή τυχαία σειρά βάσει του πίνακα.",
        "btnAudioTestMtoW_t": "Είναι φωνητική δοκιμή.\nΓράψε τη λέξη αφού ακούσεις τον ήχο.",
        "btnAudioTestMtoW": "Φωνητική δοκιμή\nαπό σημασία",
        "cbbBaseLang": "Επέλεξε τη γλώσσα σου.",
        "btnPractice_t": "Η λειτουργία εξάσκησης είναι ανοιχτού τύπου, όπου ο πίνακας παραμένει ορατός.\nΟι σωστές ή λάθος απαντήσεις σε αυτή τη λειτουργία δεν επηρεάζουν την ακρίβεια.",
        "btnPractice": "Εξάσκηση",
        "btnAudioTestDictation_t": "Είναι υπαγόρευση.\nΓράψε τη λέξη αφού την ακούσεις.",
        "btnAudioTestDictation": "Υπαγόρευση",
        "btnTextTestMtoW_t": "Είναι δοκιμή κειμένου\nγράψε τη λέξη από τη σημασία.",
        "btnTextTestMtoW": "Δοκιμή κειμένου\nαπό σημασία",
        "btn_browser_t": "Αναζήτησε τη λέξη που έχεις επιλέξει στο Google.\nΘα ανοίξει ένα παράθυρο περιηγητή.\n(Συντόμευση: F10)",
        "btn_browser": "Αναζήτηση",
        "btnDeleteScores_t": "Διαγράφει όλα τα αποτελέσματα του τεστ εκτός από τον αριθμό, τη λέξη και τη σημασία.",
        "btnDeleteScores": "Διαγραφή αποτελεσμάτων",
        "btnAlignCellsWidth_t": "Προσαρμόζει αυτόματα το πλάτος των στηλών του πίνακα.",
        "btnAlignCellsWidth": "Ευθυγράμμιση πλάτους",
        "btnAutoInputNumbers_t": "Εισάγει αυτόματα όλους τους αριθμούς με μία φορά.",
        "btnAutoInputNumbers": "Εισαγωγή αριθμών",
        "label_8": "Αρχείο λέξεων",
        "cbbWordFile": "Μπορείς να επιλέξεις ένα αρχείο λέξεων.\nΧρησιμοποίησε τη ροδέλα του ποντικιού για γρήγορη κύλιση.\nΓια να επαναεπιλέξεις αρχείο, κύλησε στην κορυφή.",
        "btnWordFileOpen_t": "Φορτώνει το αρχείο λέξεων",
        "btnWordFileOpen": "Άνοιγμα αρχείου λέξεων",
        "btnRefreshWordList_t": "Αν έχεις προσθέσει νέο αρχείο, κάνε κλικ σε αυτό το κουμπί για να το προσθέσεις στη λίστα.",
        "btnRefreshWordList": "Ανανέωση λίστας αρχείων",
        "btnDeleteWordFile_t": "Διαγράφει το επιλεγμένο αρχείο. \n Αν είναι δυνατόν, μην το διαγράψεις — φύλαξέ το για μελλοντικά τεστ.",
        "btnDeleteWordFile": "Διαγραφή αρχείου λέξεων",
        "btnMergeFiles_t": "Συγχώνευσε πολλά αρχεία λέξεων σε ένα.",
        "btnMergeFiles": "Συγχώνευση αρχείων",
        "btnDivideFile_t": "Διαίρεσε τις λέξεις και αποθήκευσέ τις σε άλλο αρχείο.\nΕπίλεξε πολλές λέξεις και πάτησε το κουμπί.",
        "btnDivideFile": "Διαίρεση λέξεων",
        "label_9": "Τύπος δοκιμής",
        "chbAllWords": "Όλες οι λέξεις",
        "chbAllWords_t": "Θα κάνεις τεστ με όλες τις λέξεις",
        "chbOnlyIncorrects": "Λάθη",
        "chbOnlyIncorrects_t": "Θα κάνεις τεστ μόνο με τις λανθασμένες απαντήσεις",
        "chbOnlyLowRates": "Ποσοστά",
        "chbOnlyLowRates_t": "Κατά τη διάρκεια της δοκιμής, θα περιλαμβάνονται μόνο λέξεις με ποσοστό ακρίβειας κάτω από το καθορισμένο όριο.",
        "label_10": "κάτω από",
        "tbWordList0": "Αρ.",
        "tbWordList1": "Λέξη",
        "tbWordList2": "Σημασία",
        "tbWordList3": "Σύγκριση",
        "tbWordList4": "Αριθμός σωστών",
        "tbWordList5": "Ποσοστό",
        "tbWordList6": "Πρόσφατος χρόνος",
        "tbWordList7": "Ταχύτερος χρόνος",
        "tbWordList8": "Τελευταίο αποτέλεσμα",
        "tbWordList9": "Ημερομηνία & ώρα τελευταίου τεστ",
        "lbWordsCounter": "Απομένουν: N/N",
        "lbTimer": "00:00:00.000",
        "lbThreeCount": "Καταμέτρηση",
        "label_11": "Θέμα:",
        "label_cbbLanguages": "Γλώσσα:",
        "label_12": "Ένταση:",
        "label_cbbFontSetting": "Γραμματοσειρά",
        "label_cbbFontSetting_tolearn": "Γλώσσα προς εκμάθηση",
        "txtVolume": "Ένταση εισόδου",
        "lbLastTest": "Πέρασαν n ημέρες από την τελευταία δοκιμή",
        "cbbTheme": "Άλλαξε θέμα όταν βαριέσαι για να ενισχύσεις τη συγκέντρωσή σου.",
        "btnPrintWords": "Εκτύπωση",
        "btnPrintWords_t": "Εκτύπωσε τις λέξεις και τις σημασίες από τον πίνακα.\nΜπορείς να τις επανεξετάσεις ακόμα και εκτός προγράμματος.",
        "cbbPitchPreset_list":{
            "lowest_slow": "Πιο χαμηλός τόνος & Αργό",
            "lowest_normal": "Πιο χαμηλός τόνος & Κανονικό",
            "lowest_fast": "Πιο χαμηλός τόνος & Γρήγορο",
            "low_slow": "Χαμηλός τόνος & Αργό",
            "low_normal": "Χαμηλός τόνος & Κανονικό",
            "low_fast": "Χαμηλός τόνος & Γρήγορο",
            "slow": "Αργό",
            "normal": "Κανονικό",
            "fast": "Γρήγορο",
            "high_slow": "Υψηλός τόνος & Αργό",
            "high_normal": "Υψηλός τόνος & Κανονικό",
            "high_fast": "Υψηλός τόνος & Γρήγορο",
            "random_preset": "Τυχαία ρύθμιση",
            "everytime_random_preset": "Τυχαία ρύθμιση κάθε φορά",
            "random_pitch": "Τυχαίος τόνος",
            "everytime_random_pitch": "Τυχαίος τόνος κάθε φορά",
            "random_speed": "Τυχαία ταχύτητα",
            "everytime_random_speed": "Τυχαία ταχύτητα κάθε φορά",
            "random_pitch_speed": "Τυχαίος τόνος & ταχύτητα",
            "everytime_random_pitch_speed": "Τυχαίος τόνος & ταχύτητα κάθε φορά",
            "user": "Ορισμένο από τον χρήστη",
        },
        "cbbTestType_list": {
            "Descending": "Φθίνουσα",
            "Ascending": "Αύξουσα",
            "Random": "Τυχαία",
        },
        "cbbPlayType_list": {
            "Descending": "Φθίνουσα",
            "Ascending": "Αύξουσα",
            "Random": "Τυχαία",
        },
        "cbbTheme_list": {
            "Default": "Προεπιλογή",
            "Dark": "Σκοτεινό",
            "Emerald": "Σμαραγδένιο",
            "Pink": "Ροζ",
            "Evening_Sky": "Απογευματινός Ουρανός",
            "Campfire_Glow": "Λάμψη από Φωτιά Κατασκήνωσης",
            "Magma": "Μάγμα",
            "Ice": "Πάγος",
            "Space": "Διάστημα",
            "Forest": "Δάσος",
            "Rainy_Day": "Βροχερή Ημέρα",
            "Desert": "Έρημος",
            "Choco": "Σοκολάτα",
            "Navy_Admiral": "Ναύαρχος Ναυτικού",
            "Royal_Scenery": "Βασιλικό Τοπίο",
            "Clerical_Robe": "Ιερατική Ρόμπα",
            "Ancient_Egypt": "Αρχαία Αίγυπτος",
            "Gemstone": "Πολύτιμος Λίθος",
            "Go_Stones": "Πέτρες Go",
        },
        "cbbWordFile_list": {
            "no_sub_folder": "---- Δεν υπάρχουν διαθέσιμοι υποφάκελοι ----",
            "no_file_click_edit": "Δεν βρέθηκαν αρχεία. Κάνε κλικ στο 'Επεξεργασία' για να δημιουργήσεις ένα αρχείο.",
            "no_recent_file": "---- Δεν υπάρχουν πρόσφατα ανοιγμένα αρχεία ----",
            "go_to_top": "↑↑↑ Επιστροφή στην κορυφή ↑↑↑",
            "current_folder": "→→→→ Τρέχοντες φάκελοι ←←←←",
            "files_in_current_folder": "↓↓↓↓ Αρχεία στον τρέχοντα φάκελο ↓↓↓↓",
            "recent_file": "★★★★ Πρόσφατα ανοιγμένα αρχεία ★★★★",
            "oldest_tested": "✏ Το παλαιότερα εξετασμένο αρχείο ✏",
            "no_oldest_tested": "---- Δεν υπάρχει εξετασμένο αρχείο ----",
        },
        "Custom_QDialog_buttons": {
            "text_ok": "✅ OK",
            "text_cancel": "❌ Ακύρωση",
            "text_cancel_t": "❌ Ακύρωση όλων των εγγραφών και επιστροφή στη λίστα λέξεων.",
            "text_exit": "❌ Έξοδος",
            "text_exit_t": "❌ Έξοδος από τη λειτουργία επεξεργασίας.",
            "text_play": "▶️ Αναπαραγωγή",
            "text_play_t": "▶️ Αναπαραγωγή της ενότητας μεταξύ της κόκκινης και της μπλε γραμμής. \n Σε ταχύτητα αναπαραγωγής κάτω από 50, ο ήχος μπορεί να ακούγεται μηχανικός.",
            "text_stop": "⏹️ Παύση",
            "text_stop_t": "⏹️ Παύση της αναπαραγωγής.",
            "text_save": "💾 Αποθήκευση",
            "text_save_t": "💾 Αποθήκευση του επιλεγμένου ήχου.",
            "text_delete": "🗑️ Διαγραφή",
            "text_area_save": "💾 Αποθήκευση επιλεγμένης περιοχής",
            "text_area_save_t": "💾 Αποθήκευση του ήχου μεταξύ της κόκκινης και της μπλε γραμμής.\nΑντικαθιστά το ηχογραφημένο αρχείο MP3 λέξης.",
            "text_edit": "📝 Επεξεργασία",
            "text_edit_t": "🔧 Είσοδος στη λειτουργία επεξεργασίας.",
            "text_test_done": "❌ Τέλος δοκιμής",
            "text_test_keep_going": "📝 Συνέχεια δοκιμής",
            "text_practic_wtom": "📤 Λέξη → Σημασία",
            "text_practic_mtow": "📥 Σημασία → Λέξη",
            "text_practic_dictation": "🗣️📝 Υπαγόρευση",
            "text_edit_justexit": "❌ Έξοδος χωρίς αποθήκευση",
            "text_edit_override": "💾📥 Αντικατάσταση",
            "text_edit_save_othername": "💾 Αποθήκευση ως",
            "text_edit_keep_editing": "📝 Συνέχιση επεξεργασίας",
            "text_select": "💾 Επιλογή",
            "text_test_all_word": "📝 Δοκιμή όλων των λέξεων",
        },
        "Custom_QDialog_label_title": {
            "text_exit": "❌ Έξοδος",
            "text_save": "💾 Αποθήκευση",
            "text_warning": "⚠️ Προειδοποίηση",
            "text_select_device": "🛠️ Επιλογή συσκευής",
            "text_recording_complete": "🎉 Η εγγραφή ολοκληρώθηκε",
            "text_aleart": "❗ Ειδοποίηση",
            "text_complete": "🎉 Ολοκληρώθηκε",
            "text_error": "🚨 Σφάλμα",
            "text_result": "📊 Αποτελέσματα δοκιμής",
            "text_select_practice_mode": "🎯 Επιλογή τρόπου εξάσκησης",
            "text_cancel": "❌ Ακύρωση",
            "text_delete_file": "❌💾 Διαγραφή αρχείου",
            "text_delete_complete": "✅ Η διαγραφή ολοκληρώθηκε",
            "text_audio_edit": "🎶🔧 Επεξεργασία ήχου",
            "text_PrintOptionsDialog": "📝 Ρυθμίσεις εκτύπωσης",
            "text_show_device_selection_dialog": "🔧 Επιλογή συσκευής εγγραφής",
        },
        "Custom_QDialog_label_content": {
            "audio_editor_start": "Έναρξη:",
            "audio_editor_current": "Θέση αναπαραγωγής:",
            "audio_editor_end": "Τέλος:",
            "audio_editor_speed_control": "Έλεγχος ταχύτητας",
            "audio_editor_done": "Είσαι σίγουρος ότι θέλεις να εξέλθεις;\nΟι μη αποθηκευμένες εγγραφές θα χαθούν.\n(Τα αποθηκευμένα αρχεία θα διατηρηθούν)",
            "audio_editor_save_succesed": "Η εγγραφή αποθηκεύτηκε με επιτυχία!",
            "audio_editor_save_failed": "Αποτυχία αποθήκευσης εγγραφής:",
            "print_choose_to_print": "Επέλεξε τι θέλεις να εκτυπώσεις:",
            "print_font_size": "Επέλεξε μέγεθος γραμματοσειράς:",
            "search_selected_word_no_word": "Δεν έχει επιλεγεί λέξη!",
            "search_selected_word_choose_word": "Παρακαλώ επίλεξε μια λέξη από τον πίνακα!",
            "show_overlay_recording": "🔴 Εγγραφή...",
            "show_overlay_press_ESC": "Πάτησε ESC για να σταματήσεις την εγγραφή",
            "select_device_choose_device": "Παρακαλώ επίλεξε συσκευή εγγραφής.",
            "show_edit_or_save_dialog_recording_done": "Η εγγραφή ολοκληρώθηκε. Τι θέλεις να κάνεις;",
            "start_auto_play_not_condition": "Καμία λέξη δεν πληροί τις προϋποθέσεις!",
            "handle_header_click_h": "ώ",
            "handle_header_click_m": "λ",
            "handle_header_click_s": "δ",
            "delete_temp_files_delete_succesed": "Η διαγραφή των mp3 ολοκληρώθηκε!",
            "delete_temp_files_delete_error": "Προέκυψε σφάλμα κατά τη διαγραφή των αρχείων:",
            "delete_temp_no_folder": "Ο φάκελος MP3 δεν υπάρχει.",
            "delete_temp_no_selection": "Δεν έχει επιλεγεί λέξη.",
            "delete_temp_file_not_found": "Το αρχείο mp3 της επιλεγμένης λέξης λείπει ή δεν μπορεί να βρεθεί.",
            "show_completion_message": "Όλα τα αρχεία ήχου έχουν δημιουργηθεί.",
            "new_time_record_check_no_record": "Καμία καταγραφή",
            "toggle_test_mode_no_condition": "Δεν πληρούνται οι προϋποθέσεις για το τεστ!\nΘέλεις να εξετάσεις όλες τις λέξεις αντί αυτού;",
            "toggle_test_mode_surt_to_end": "Αν τερματίσεις το τεστ τώρα, αυτή η προσπάθεια δεν θα μετρηθεί.\nΘέλεις να το ολοκληρώσεις;",
            "toggle_practice_mode_no_word": "Δεν δημιουργήθηκαν ερωτήσεις λόγω μη συμβατών συνθηκών.\nΈλεγξε τις ρυθμίσεις σου.\n(π.χ. Επιλέχθηκαν μόνο λάθος απαντήσεις αλλά δεν υπάρχουν τέτοιες)",
            "display_result_correct_num": "Σωστές απαντήσεις:",
            "display_result_total_time": "Συνολικός χρόνος δοκιμής:",
            "show_feedback_label_cor": "Σωστό!",
            "show_feedback_var_cor": "Σωστό",
            "show_feedback_label_incor": "Λάθος...",
            "show_feedback_var_incor": "Λάθος",
            "show_feedback_label_none": "Άγνωστη τιμή",
            "start_test_forTest_des": "Φθίνουσα",
            "start_test_forTest_as": "Αύξουσα",
            "start_test_forTest_rd": "Τυχαία",
            "next_question_forTest_remain": "Απομένουν ερωτήσεις:",
            "next_question_forTest_start": "Έναρξη!",
            "keyPressEvent_label": "-Ποσοστό ακρίβειας",
            "number_checker_before_test_error1": "Ο αριθμός πρέπει να είναι θετικός ακέραιος μεγαλύτερος του 0.",
            "number_checker_before_test_error2": "Οι αριθμοί πρέπει να είναι θετικοί ακέραιοι.\nΧρησιμοποίησε το κουμπί 'Αυτόματη εισαγωγή αριθμών' για σωστή καταχώρηση.",
            "number_checker_before_test_label": "Υπάρχουν κενά πεδία στη λέξη ή στη σημασία.\nΠαρακαλώ συμπλήρωσέ τα μέσω επεξεργασίας.",
            "toggle_practice_mode_wtom": "⏭️ Λέξη → Σημασία",
            "toggle_practice_mode_mtow": "⏮️ Σημασία → Λέξη",
            "toggle_practice_mode_dict": "🗣️📝 Υπαγόρευση",
            "toggle_edit_mode_label": "Υπάρχουν κενά πεδία. Παρακαλώ συμπλήρωσέ τα όλα.",
            "load_csv_label": "Παρουσιάστηκε σφάλμα κατά την ανάγνωση του αρχείου CSV:",
            "show_save_options_label": "Πώς θέλεις να διαχειριστείς τις αλλαγές;",
            "save_as_new_file_dialog_title": "💾 Αποθήκευση ως",
            "delete_current_file_sure_to_delete": "Είσαι σίγουρος ότι θέλεις να διαγράψεις αυτό το αρχείο;",
            "delete_current_file_delete_done": "Το αρχείο διαγράφηκε.",
            "delete_current_file_delete_error": "Παρουσιάστηκε σφάλμα κατά τη διαγραφή του αρχείου:",
            "delete_current_file_delete_cancel": "Η διαγραφή του αρχείου ακυρώθηκε.",
            "delete_current_file_no_file": "Δεν υπάρχει αρχείο προς διαγραφή.",
            "save_changes_label": "Υπάρχουν κενές γραμμές. Παρακαλώ συμπλήρωσέ τις όλες.",
            "on_combobox_changed_error": "Το αρχείο δεν βρέθηκε:",
            "update_last_test_label_y": "Έτος",
            "update_last_test_label_m": "Μήνας",
            "update_last_test_label_d": "Ημέρα",
            "update_last_test_label_resisted_file": "Καταχωρημένο αρχείο",
            "update_last_test_label_last_test": " | Τελευταίο τεστ ",
            "update_last_test_label_d_passed": "ημέρες πριν",
            "PrintOptionsDialog_wordonly": "Εκτύπωση μόνο λέξεων",
            "PrintOptionsDialog_meaningonly": "Εκτύπωση μόνο σημασιών",
            "PrintOptionsDialog_wordmeaning": "Εκτύπωση λέξεων και σημασιών",
            "PrintOptionsDialog_selectcontent": "Επέλεξε στοιχεία για εκτύπωση:",
            "PrintOptionsDialog_fontsize": "Επέλεξε μέγεθος γραμματοσειράς:",
            "show_practice_choice_dialog_select_mode": "Επέλεξε τρόπο εξάσκησης",
            "update_last_test_label_no_file": "Το αρχείο δεν υπάρχει.",
        },
        "table_values": {
            "correct": "σωστό",
            "wrong": "λάθος",
            "no_record": "χωρίς καταγραφή",
        },
        "file_merging": {
            "title": "Συγχώνευση Αρχείων Λέξεων",
            "btn_file_open": "Εισαγωγή αρχείου",
            "btn_except_file": "Εξαίρεση αρχείου",
            "btn_files_to_merge": "Συγχώνευση αρχείων",
            "btn_exit": "Κλείσιμο",
            "dialog_open_title": "Επιλογή αρχείου",
            "dialog_save_title": "Αποθήκευση συγχωνευμένου αρχείου",
            "merging_completed": "Τα αρχεία συγχωνεύτηκαν με επιτυχία.",
            "completed": "Ολοκληρώθηκε",
            "merging_error": "Προέκυψε σφάλμα κατά τη συγχώνευση:",
            "error": "Σφάλμα",
            "no_file_to_merge": "Δεν υπάρχουν αρχεία για συγχώνευση.",
            "no_file_to_merge": "Δεν υπάρχουν αρχεία για συγχώνευση.",
            "warning": "Προειδοποίηση",
            "overwrite_warning": "Το αρχείο που προσπαθείς να αποθηκεύσεις είναι ένα από τα αρχεία προς συγχώνευση.\nΘέλεις να το αντικαταστήσεις;",
            "yes": "Ναι (Αντικατάσταση)",
            "no": "Όχι (Αποθήκευση ως)",

        },
        "file_divide": {
            "file_not_selected_title": "Ειδοποίηση",
            "file_not_selected": "Επίλεξε τις λέξεις που θέλεις να αποθηκεύσεις.",
            "file_saving": "Αποθήκευση",
            "file_saved_title": "Ολοκληρώθηκε",
            "file_saved": "Οι επιλεγμένες λέξεις αποθηκεύτηκαν.",
        },
        "jsonerror_nofile": "Δεν υπάρχουν ρυθμίσεις. Θα χρησιμοποιηθούν οι προεπιλεγμένες.",
        "jsonerror_valueerror": "Σφάλμα στις ρυθμίσεις. Θα χρησιμοποιηθούν οι προεπιλεγμένες.",
        "wordfileloaded_nofile1": "Δεν υπάρχει αρχείο για φόρτωση.",
        "wordfileloaded_nofile2": "Κάνε κλικ στην Επεξεργασία για να δημιουργήσεις τη λίστα λέξεων.",
        "wordfileloaded_success1": "Το αρχείο φορτώθηκε με επιτυχία.",
        "wordfileloaded_success2": "Εξασκήσου στις λέξεις μέσω εξάσκησης ή δοκιμής.",
        "test_contition_error1": "Η δοκιμή ολοκληρώθηκε!",
        "test_contition_error2": "Ρύθμισε τις συνθήκες της δοκιμής και δοκίμασε ξανά.",
        "tested_well1": "Η δοκιμή ολοκληρώθηκε!",
        "tested_well2": "Έλεγξε τα αποτελέσματά σου και συνέχισε την εξάσκηση.",
        "practicing_done1": "Η εξάσκηση ολοκληρώθηκε!",
        "practicing_done2": "Αν είσαι έτοιμος, προχώρησε στην πραγματική δοκιμή!",
        "is_editing1": "Ctrl + Enter: Προσθήκη γραμμής",
        "is_editing2": "Πάτησε ESC για έξοδο από την επεξεργασία, μετά Ctrl + Backspace: Διαγραφή γραμμής",
        },
}