# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap, QFont
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel, QHBoxLayout, QVBoxLayout, QWidget, QComboBox, QListView
from PyQt5.QtCore import Qt, QPoint, QThread, pyqtSignal
from theme_colors import THEME_COLORS
import os
import sys
import ctypes
from ctypes import wintypes

class CustomTitleBar(QWidget):
    """ 🎨 커스텀 제목 표시줄 (닫기, 최소화 버튼 포함) """
    update_signal = pyqtSignal(str)
    
    def __init__(self, parent, title_text, theme_name, window_type = "main"):
                
        theme = THEME_COLORS.get(theme_name, "basic")

        super().__init__(parent)
        self.parent = parent
        self.setFixedHeight(40)  # 제목 표시줄 높이
        self.window_type = window_type

        # 🔹 타이틀 (제목)
        self.title = QLabel(f"{title_text}", self)
        self.title.setStyleSheet(f"color: {theme['button_text']}; background-color: {theme['button_bg']};")
        self.title.setAlignment(Qt.AlignCenter)
        
        # 🔹 아이콘 QLabel 추가
        self.icon_label = QtWidgets.QLabel(self)
        pixmap = QPixmap(self.resource_path("myicon.ico"))
        self.icon_label.setPixmap(pixmap.scaled(24, 24, Qt.KeepAspectRatio, Qt.SmoothTransformation))  # ✅ 크기 조정
        self.icon_label.setStyleSheet("background-color: transparent; border: 0px;")

        if self.window_type == "main":
            # 🔹 최소화 버튼
            self.minimize_button = QPushButton("−", self)
            self.minimize_button.setObjectName("minimize_button")
            self.minimize_button.setFixedSize(30, 30)
            self.minimize_button.clicked.connect(self.parent.showMinimized)
        
            # 🔹 최대화/복귀 버튼
            self.maximize_button = QtWidgets.QPushButton("🗖", self)  # 기본 최대화 아이콘
            self.maximize_button.setObjectName("maximize_button")
            self.maximize_button.setFixedSize(30, 30)
            self.maximize_button.clicked.connect(self.toggle_maximize_restore)
        
        # 🔹 닫기 버튼
        self.close_button = QPushButton("✕", self)
        self.close_button.setObjectName("close_button")
        self.close_button.setFixedSize(30, 30)
        self.close_button.clicked.connect(self.parent.close)

        # 🔹 레이아웃 설정
        layout = QHBoxLayout()
        layout.addWidget(self.icon_label)
        layout.addWidget(self.title, 1)
        if self.window_type == "main":
            layout.addWidget(self.minimize_button)
            layout.addWidget(self.maximize_button)
        layout.addWidget(self.close_button)
        layout.setContentsMargins(10, 5, 10, 5)
        self.setLayout(layout)

        # 🔹 스타일 적용
        self.setStyleSheet(f"""
            QWidget {{
                background-color: #333333;
                border-bottom: 2px solid #222222;
            }}
            QPushButton {{
                background: {theme['button_bg']};
                color: {theme['button_text']};
                font-size: 14px;
                border: 0px solid #4F4F4F;
                border-radius: 4px;
            }}
            QPushButton:hover {{
                color: {theme['button_hover_text']};
                background-color: {theme['button_hover_bg']};
            }}
            QLabel {{
                background-color: {theme['button_disible_bg']};
                color: {theme['button_text']};
                border-radius: 4px;
                border: 0px;
            }}
        """)
        
    def resource_path(self, relative_path):
        if getattr(sys, 'frozen', False):
            base_path = sys._MEIPASS
        else:
            base_path = os.path.dirname(__file__)
        return os.path.join(base_path, relative_path)

    def mouseDoubleClickEvent(self, event):
        """📌 더블클릭 시 창 최대화/복구 기능"""
        if event.button() == Qt.LeftButton and self.window_type == "main":
            self.toggle_maximize_restore()
            
    # 🔥 창 이동 기능 구현
    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton and not self.parent.isMaximized():
            self.drag_position = event.globalPos() - self.parent.frameGeometry().topLeft()
            event.accept()
            
    def toggle_maximize_restore(self):
        GWL_STYLE = -16
        WS_THICKFRAME = 0x00040000
        SWP_NOMOVE = 0x0002
        SWP_NOSIZE = 0x0001
        SWP_FRAMECHANGED = 0x0020
        hwnd = int(self.parent.winId())  # 부모 윈도우의 HWND 얻기
        
        """ 🔄 최대화/복귀 버튼 기능 """
        if self.parent.isMaximized():
            # 👇 복귀: 크기 조절 프레임 다시 추가
            style = ctypes.windll.user32.GetWindowLongW(hwnd, GWL_STYLE)
            style |= WS_THICKFRAME
            ctypes.windll.user32.SetWindowLongW(hwnd, GWL_STYLE, style)

            ctypes.windll.user32.SetWindowPos(hwnd, 0, 0, 0, 0, 0,
                SWP_NOMOVE | SWP_NOSIZE | SWP_FRAMECHANGED)

            self.parent.showNormal()
            self.parent.setGeometry(100, 100, 800, 600)  # 원하는 위치/크기
            self.maximize_button.setText("🗖")  # 최대화 아이콘
        else:
        # 👇 최대화: 크기 조절 프레임 제거 → 전체화면에 생기는 여백 방지
            style = ctypes.windll.user32.GetWindowLongW(hwnd, GWL_STYLE)
            style &= ~WS_THICKFRAME
            ctypes.windll.user32.SetWindowLongW(hwnd, GWL_STYLE, style)

            ctypes.windll.user32.SetWindowPos(hwnd, 0, 0, 0, 0, 0,
                SWP_NOMOVE | SWP_NOSIZE | SWP_FRAMECHANGED)

            screen = QApplication.primaryScreen().availableGeometry()
            self.parent.setGeometry(screen)  # 정확한 최대화 영역
            self.parent.showMaximized()
            self.maximize_button.setText("🗗")  # 복귀 아이콘
        
    def mouseMoveEvent(self, event):
        if event.buttons() == Qt.LeftButton and not self.parent.isMaximized():
            self.parent.move(event.globalPos() - self.drag_position)
            event.accept()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QIcon("myicon.ico"))
        MainWindow.resize(1279, 878)

        # ✅ 기본 타이틀바 제거
        MainWindow.setWindowFlags(Qt.FramelessWindowHint | Qt.Window)
        
        # Windows API를 사용해 WS_THICKFRAME 추가
        hwnd = int(self.winId())
        style = ctypes.windll.user32.GetWindowLongW(hwnd, -16)  # GWL_STYLE = -16
        style |= 0x00040000  # WS_SIZEBOX (aka WS_THICKFRAME)
        ctypes.windll.user32.SetWindowLongW(hwnd, -16, style)

        # 스타일 변경 반영
        ctypes.windll.user32.SetWindowPos(hwnd, 0, 0, 0, 0, 0,
            0x0002 | 0x0001 | 0x0020)  # SWP_NOMOVE | SWP_NOSIZE | SWP_FRAMECHANGED
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # ✅ 🔹 새로운 메인 레이아웃 (QVBoxLayout 사용)
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(5, 5, 5, 5)  # ✅ 여백 제거
        self.main_layout.setSpacing(4)  # ✅ 간격 제거

        # ✅ 🔹 커스텀 타이틀바 추가
        self.title_bar = CustomTitleBar(MainWindow, "단어 테스트기 3 - 모두 힘내서 외국어 연습합시다! -외저씨올림-", "basic", "main")
        self.title_bar.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.main_layout.addWidget(self.title_bar)  # ✅ 타이틀바를 상단에 추가

        # ✅ 🔹 기존 레이아웃 추가 (타이틀바 아래에)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_layout.addLayout(self.gridLayout_2)  # ✅ 기존 레이아웃을 아래쪽에 추가
        
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(75, 55))
        self.label.setMaximumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(75, 55))
        self.label_2.setMaximumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtMeaningInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtMeaningInput.setMinimumSize(QtCore.QSize(250, 65))
        self.txtMeaningInput.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(36)
        self.txtMeaningInput.setFont(font)
        self.txtMeaningInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtMeaningInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtMeaningInput.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtMeaningInput.setObjectName("txtMeaningInput")
        self.gridLayout_4.addWidget(self.txtMeaningInput, 1, 1, 1, 1)
        self.txtWordInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtWordInput.setMinimumSize(QtCore.QSize(250, 60))
        self.txtWordInput.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(36)
        self.txtWordInput.setFont(font)
        self.txtWordInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtWordInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtWordInput.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtWordInput.setObjectName("txtWordInput")
        self.gridLayout_4.addWidget(self.txtWordInput, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDeleteAudios = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteAudios.setMinimumSize(QtCore.QSize(125, 25))
        self.btnDeleteAudios.setMaximumSize(QtCore.QSize(185, 25))
        self.btnDeleteAudios.setObjectName("btnDeleteAudios")
        self.horizontalLayout.addWidget(self.btnDeleteAudios)
        self.btnDeleteNowAudio = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteNowAudio.setMinimumSize(QtCore.QSize(125, 25))
        self.btnDeleteNowAudio.setMaximumSize(QtCore.QSize(185, 25))
        self.btnDeleteNowAudio.setObjectName("btnDeleteNowAudio")
        self.horizontalLayout.addWidget(self.btnDeleteNowAudio)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(600, 25))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.btnRecord = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecord.setMinimumSize(QtCore.QSize(55, 25))
        self.btnRecord.setMaximumSize(QtCore.QSize(155, 25))
        self.btnRecord.setObjectName("btnRecord")
        self.horizontalLayout.addWidget(self.btnRecord)
        self.btnMakeAudios = QtWidgets.QPushButton(self.centralwidget)
        self.btnMakeAudios.setMinimumSize(QtCore.QSize(100, 25))
        self.btnMakeAudios.setMaximumSize(QtCore.QSize(200, 25))
        self.btnMakeAudios.setObjectName("btnMakeAudios")
        self.horizontalLayout.addWidget(self.btnMakeAudios)
        self.btnOpenThisWordsMP3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenThisWordsMP3.setMinimumSize(QtCore.QSize(125, 25))
        self.btnOpenThisWordsMP3.setMaximumSize(QtCore.QSize(225, 25))
        self.btnOpenThisWordsMP3.setObjectName("btnOpenThisWordsMP3")
        self.horizontalLayout.addWidget(self.btnOpenThisWordsMP3)
        self.btnAutoPlay = QtWidgets.QPushButton(self.centralwidget)
        self.btnAutoPlay.setMinimumSize(QtCore.QSize(100, 25))
        self.btnAutoPlay.setMaximumSize(QtCore.QSize(200, 25))
        self.btnAutoPlay.setObjectName("btnAutoPlay")
        self.horizontalLayout.addWidget(self.btnAutoPlay)
        self.cbbPlayType = QtWidgets.QComboBox(self.centralwidget)
        self.cbbPlayType.setMinimumSize(QtCore.QSize(100, 30))
        self.cbbPlayType.setMaximumSize(QtCore.QSize(200, 30))
        self.cbbPlayType.setObjectName("cbbPlayType")
        font = self.cbbPlayType.font()
        font.setPointSize(9)
        self.cbbPlayType.setFont(font)
        self.cbbPlayType.view().setSpacing(4)  # 항목 간 간격 조절
        self.horizontalLayout.addWidget(self.cbbPlayType)
        self.chbToReadMeaning = QtWidgets.QCheckBox(self.centralwidget)
        self.chbToReadMeaning.setMinimumSize(QtCore.QSize(75, 25))
        self.chbToReadMeaning.setMaximumSize(QtCore.QSize(175, 25))
        self.chbToReadMeaning.setObjectName("chbToReadMeaning")
        self.horizontalLayout.addWidget(self.chbToReadMeaning)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(20, 25))
        self.label_13.setMaximumSize(QtCore.QSize(120, 25))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.txtAutoAudioDuration = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAutoAudioDuration.setMinimumSize(QtCore.QSize(50, 25))
        self.txtAutoAudioDuration.setMaximumSize(QtCore.QSize(150, 25))
        self.txtAutoAudioDuration.setObjectName("txtAutoAudioDuration")
        self.horizontalLayout.addWidget(self.txtAutoAudioDuration)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(20, 25))
        self.label_14.setMaximumSize(QtCore.QSize(120, 25))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.slbPitchControler = QtWidgets.QSlider(self.centralwidget)
        self.slbPitchControler.setMinimumSize(QtCore.QSize(125, 0))
        self.slbPitchControler.setOrientation(QtCore.Qt.Horizontal)
        self.slbPitchControler.setObjectName("slbPitchControler")
        self.horizontalLayout_2.addWidget(self.slbPitchControler)
        self.txtPitchControler = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPitchControler.setMinimumSize(QtCore.QSize(55, 25))
        self.txtPitchControler.setMaximumSize(QtCore.QSize(55, 25))
        #self.txtPitchControler.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPitchControler.setObjectName("txtPitchControler")
        self.horizontalLayout_2.addWidget(self.txtPitchControler)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.slbSpeedControler = QtWidgets.QSlider(self.centralwidget)
        self.slbSpeedControler.setMinimumSize(QtCore.QSize(125, 0))
        self.slbSpeedControler.setOrientation(QtCore.Qt.Horizontal)
        self.slbSpeedControler.setObjectName("slbSpeedControler")
        self.horizontalLayout_2.addWidget(self.slbSpeedControler)
        self.txtSpeedControler = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSpeedControler.setMinimumSize(QtCore.QSize(55, 25))
        self.txtSpeedControler.setMaximumSize(QtCore.QSize(55, 25))
        #self.txtSpeedControler.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSpeedControler.setObjectName("txtSpeedControler")
        self.horizontalLayout_2.addWidget(self.txtSpeedControler)
        self.cbbPitchPreset = QtWidgets.QComboBox(self.centralwidget)
        self.cbbPitchPreset.setObjectName("cbbPitchPreset")
        self.cbbPitchPreset.setMinimumSize(QtCore.QSize(125, 30))
        self.cbbPitchPreset.setMaximumSize(QtCore.QSize(225, 30))
        font = self.cbbPitchPreset.font()
        font.setPointSize(9)
        self.cbbPitchPreset.setFont(font)
        self.cbbPitchPreset.view().setSpacing(4)  # 항목 간 간격 조절
        self.horizontalLayout_2.addWidget(self.cbbPitchPreset)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cbbLangToLearn = QtWidgets.QComboBox(self.centralwidget)
        self.cbbLangToLearn.setMinimumSize(QtCore.QSize(250, 30))
        self.cbbLangToLearn.setMaximumSize(QtCore.QSize(250, 30))
        self.cbbLangToLearn.setObjectName("cbbLangToLearn")
        font = self.cbbLangToLearn.font()
        font.setPointSize(9)
        self.cbbLangToLearn.setFont(font)
        self.cbbLangToLearn.view().setSpacing(4)  # 항목 간 간격 조절
        self.gridLayout.addWidget(self.cbbLangToLearn, 0, 9, 1, 1)
        self.btnTextTestWtoM = QtWidgets.QPushButton(self.centralwidget)
        self.btnTextTestWtoM.setMinimumSize(QtCore.QSize(100, 55))
        self.btnTextTestWtoM.setMaximumSize(QtCore.QSize(200, 55))
        self.btnTextTestWtoM.setObjectName("btnTextTestWtoM")
        self.gridLayout.addWidget(self.btnTextTestWtoM, 0, 2, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(75, 25))
        self.label_5.setMaximumSize(QtCore.QSize(175, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 7, 1, 1)
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setMinimumSize(QtCore.QSize(100, 55))
        self.btnEdit.setMaximumSize(QtCore.QSize(200, 55))
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout.addWidget(self.btnEdit, 0, 1, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(75, 25))
        self.label_7.setMaximumSize(QtCore.QSize(175, 25))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 8, 1, 1)
        self.btnAudioTestWtoM = QtWidgets.QPushButton(self.centralwidget)
        self.btnAudioTestWtoM.setMinimumSize(QtCore.QSize(100, 55))
        self.btnAudioTestWtoM.setMaximumSize(QtCore.QSize(200, 55))
        self.btnAudioTestWtoM.setObjectName("btnAudioTestWtoM")
        self.gridLayout.addWidget(self.btnAudioTestWtoM, 0, 4, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(75, 25))
        self.label_6.setMaximumSize(QtCore.QSize(175, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 8, 1, 1)
        self.cbbTestType = QtWidgets.QComboBox(self.centralwidget)
        self.cbbTestType.setObjectName("cbbTestType")
        font = self.cbbTestType.font()
        font.setPointSize(9)
        self.cbbTestType.setFont(font)
        self.cbbTestType.setMinimumSize(QtCore.QSize(75, 30))
        self.cbbTestType.setMaximumSize(QtCore.QSize(175, 30))
        self.cbbTestType.view().setSpacing(4)  # 항목 간 간격 조절
        self.gridLayout.addWidget(self.cbbTestType, 1, 7, 1, 1)
        self.btnAudioTestMtoW = QtWidgets.QPushButton(self.centralwidget)
        self.btnAudioTestMtoW.setMinimumSize(QtCore.QSize(100, 55))
        self.btnAudioTestMtoW.setMaximumSize(QtCore.QSize(200, 55))
        self.btnAudioTestMtoW.setObjectName("btnAudioTestMtoW")
        self.gridLayout.addWidget(self.btnAudioTestMtoW, 0, 5, 2, 1)
        self.cbbBaseLang = QtWidgets.QComboBox(self.centralwidget)
        self.cbbBaseLang.setMinimumSize(QtCore.QSize(250, 30))
        self.cbbBaseLang.setMaximumSize(QtCore.QSize(350, 30))
        self.cbbBaseLang.setObjectName("cbbBaseLang")
        font = self.cbbBaseLang.font()
        font.setPointSize(9)
        self.cbbBaseLang.setFont(font)
        self.cbbBaseLang.view().setSpacing(4)  # 항목 간 간격 조절
        self.gridLayout.addWidget(self.cbbBaseLang, 1, 9, 1, 1)
        self.btnPractice = QtWidgets.QPushButton(self.centralwidget)
        self.btnPractice.setMinimumSize(QtCore.QSize(100, 55))
        self.btnPractice.setMaximumSize(QtCore.QSize(200, 55))
        self.btnPractice.setObjectName("btnPractice")
        self.gridLayout.addWidget(self.btnPractice, 0, 0, 2, 1)
        self.btnAudioTestDictation = QtWidgets.QPushButton(self.centralwidget)
        self.btnAudioTestDictation.setMinimumSize(QtCore.QSize(100, 55))
        self.btnAudioTestDictation.setMaximumSize(QtCore.QSize(200, 55))
        self.btnAudioTestDictation.setObjectName("btnAudioTestDictation")
        self.gridLayout.addWidget(self.btnAudioTestDictation, 0, 6, 2, 1)
        self.btnTextTestMtoW = QtWidgets.QPushButton(self.centralwidget)
        self.btnTextTestMtoW.setMinimumSize(QtCore.QSize(100, 55))
        self.btnTextTestMtoW.setMaximumSize(QtCore.QSize(200, 55))
        self.btnTextTestMtoW.setObjectName("btnTextTestMtoW")
        self.gridLayout.addWidget(self.btnTextTestMtoW, 0, 3, 2, 1)
        self.btn_browser = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browser.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_browser.setMaximumSize(QtCore.QSize(200, 25))
        self.btn_browser.setObjectName("btn_browser")
        self.gridLayout.addWidget(self.btn_browser, 0, 11, 1, 1)
        self.btnDeleteScores = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteScores.setMinimumSize(QtCore.QSize(100, 25))
        self.btnDeleteScores.setMaximumSize(QtCore.QSize(200, 25))
        self.btnDeleteScores.setObjectName("btnDeleteScores")
        self.gridLayout.addWidget(self.btnDeleteScores, 1, 11, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnAlignCellsWidth = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlignCellsWidth.setMinimumSize(QtCore.QSize(75, 25))
        self.btnAlignCellsWidth.setMaximumSize(QtCore.QSize(175, 25))
        self.btnAlignCellsWidth.setObjectName("btnAlignCellsWidth")
        self.horizontalLayout_3.addWidget(self.btnAlignCellsWidth)
        self.btnAutoInputNumbers = QtWidgets.QPushButton(self.centralwidget)
        self.btnAutoInputNumbers.setMinimumSize(QtCore.QSize(85, 25))
        self.btnAutoInputNumbers.setMaximumSize(QtCore.QSize(185, 25))
        self.btnAutoInputNumbers.setObjectName("btnAutoInputNumbers")
        self.horizontalLayout_3.addWidget(self.btnAutoInputNumbers)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(55, 25))
        self.label_8.setMaximumSize(QtCore.QSize(155, 25))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.cbbWordFile = QtWidgets.QComboBox(self.centralwidget)
        self.cbbWordFile.setObjectName("cbbWordFile")
        font = self.cbbWordFile.font()
        font.setPointSize(9)
        self.cbbWordFile.setFont(font)
        self.cbbWordFile.setMinimumSize(QtCore.QSize(300, 30))
        self.cbbWordFile.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbbWordFile.view().setSpacing(4)  # 항목 간 간격 조절
        self.horizontalLayout_3.addWidget(self.cbbWordFile)
        self.btnWordFileOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnWordFileOpen.setMinimumSize(QtCore.QSize(85, 25))
        self.btnWordFileOpen.setMaximumSize(QtCore.QSize(185, 25))
        self.btnWordFileOpen.setObjectName("btnWordFileOpen")
        self.horizontalLayout_3.addWidget(self.btnWordFileOpen)
        self.btnRefreshWordList = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefreshWordList.setMinimumSize(QtCore.QSize(85, 25))
        self.btnRefreshWordList.setMaximumSize(QtCore.QSize(185, 25))
        self.btnRefreshWordList.setObjectName("btnRefreshWordList")
        self.horizontalLayout_3.addWidget(self.btnRefreshWordList)
        self.btnDeleteWordFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteWordFile.setMinimumSize(QtCore.QSize(85, 25))
        self.btnDeleteWordFile.setMaximumSize(QtCore.QSize(185, 25))
        self.btnDeleteWordFile.setObjectName("btnDeleteWordFile")
        self.horizontalLayout_3.addWidget(self.btnDeleteWordFile)
        self.btnMergeFiles = QtWidgets.QPushButton(self.centralwidget)
        self.btnMergeFiles.setMinimumSize(QtCore.QSize(85, 25))
        self.btnMergeFiles.setMaximumSize(QtCore.QSize(185, 25))
        self.btnMergeFiles.setObjectName("btnMergeFiles")
        self.horizontalLayout_3.addWidget(self.btnMergeFiles)
        self.btnDivideFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnDivideFile.setMinimumSize(QtCore.QSize(85, 25))
        self.btnDivideFile.setMaximumSize(QtCore.QSize(185, 25))
        self.btnDivideFile.setObjectName("btnDivideFile")
        self.horizontalLayout_3.addWidget(self.btnDivideFile)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(55, 25))
        self.label_9.setMaximumSize(QtCore.QSize(155, 25))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.chbAllWords = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAllWords.setMinimumSize(QtCore.QSize(75, 25))
        self.chbAllWords.setMaximumSize(QtCore.QSize(175, 25))
        self.chbAllWords.setObjectName("chbAllWords")
        self.horizontalLayout_3.addWidget(self.chbAllWords)
        self.chbOnlyIncorrects = QtWidgets.QCheckBox(self.centralwidget)
        self.chbOnlyIncorrects.setMinimumSize(QtCore.QSize(65, 25))
        self.chbOnlyIncorrects.setMaximumSize(QtCore.QSize(165, 25))
        self.chbOnlyIncorrects.setObjectName("chbOnlyIncorrects")
        self.horizontalLayout_3.addWidget(self.chbOnlyIncorrects)
        self.chbOnlyLowRates = QtWidgets.QCheckBox(self.centralwidget)
        self.chbOnlyLowRates.setMinimumSize(QtCore.QSize(65, 25))
        self.chbOnlyLowRates.setMaximumSize(QtCore.QSize(165, 25))
        self.chbOnlyLowRates.setObjectName("chbOnlyLowRates")
        self.horizontalLayout_3.addWidget(self.chbOnlyLowRates)
        self.cbbRateFilter = QtWidgets.QComboBox(self.centralwidget)
        self.cbbRateFilter.setMinimumSize(QtCore.QSize(65, 30))
        self.cbbRateFilter.setMaximumSize(QtCore.QSize(165, 30))
        self.cbbRateFilter.setObjectName("cbbRateFilter")
        font = self.cbbRateFilter.font()
        font.setPointSize(9)
        self.cbbRateFilter.setFont(font)
        self.cbbRateFilter.view().setSpacing(4)  # 항목 간 간격 조절
        self.horizontalLayout_3.addWidget(self.cbbRateFilter)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMinimumSize(QtCore.QSize(45, 25))
        self.label_10.setMaximumSize(QtCore.QSize(145, 25))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.tbWordList = QtWidgets.QTableWidget(self.centralwidget)
        self.tbWordList.setMinimumSize(QtCore.QSize(1200, 500))
        self.tbWordList.setObjectName("tbWordList")
        self.tbWordList.setColumnCount(10)
        self.tbWordList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWordList.setHorizontalHeaderItem(9, item)
        self.gridLayout_2.addWidget(self.tbWordList, 5, 0, 2, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 4, 1, 1, 1)
        self.lbWordsCounter = QtWidgets.QLabel(self.centralwidget)
        self.lbWordsCounter.setMinimumSize(QtCore.QSize(550, 80))
        self.lbWordsCounter.setMaximumSize(QtCore.QSize(550, 80))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(48)
        self.lbWordsCounter.setFont(font)
        self.lbWordsCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.lbWordsCounter.setObjectName("lbWordsCounter")
        self.gridLayout_7.addWidget(self.lbWordsCounter, 2, 1, 1, 1)
        self.lbTimer = QtWidgets.QLabel(self.centralwidget)
        self.lbTimer.setMinimumSize(QtCore.QSize(550, 80))
        self.lbTimer.setMaximumSize(QtCore.QSize(550, 80))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(48)
        self.lbTimer.setFont(font)
        self.lbTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTimer.setObjectName("lbTimer")
        self.gridLayout_7.addWidget(self.lbTimer, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 3, 2, 1, 1)
        self.lbThreeCount = QtWidgets.QLabel(self.centralwidget)
        self.lbThreeCount.setMinimumSize(QtCore.QSize(550, 80))
        self.lbThreeCount.setMaximumSize(QtCore.QSize(550, 80))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(48)
        self.lbThreeCount.setFont(font)
        self.lbThreeCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lbThreeCount.setObjectName("lbThreeCount")
        self.gridLayout_7.addWidget(self.lbThreeCount, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 6, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.cbbTheme = QtWidgets.QComboBox(self.centralwidget)
        self.cbbTheme.setObjectName("cbbTheme")
        self.cbbTheme.setMinimumSize(QtCore.QSize(100, 25))
        self.cbbTheme.setMaximumSize(QtCore.QSize(150, 25))
        self.horizontalLayout_4.addWidget(self.cbbTheme)
        self.label_cbbLanguages = QtWidgets.QLabel(self.centralwidget)
        self.label_cbbLanguages.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_cbbLanguages)
        self.cbbLanguages = QtWidgets.QComboBox(self.centralwidget)
        self.cbbLanguages.setObjectName("cbbLanguages")
        self.cbbLanguages.setMinimumSize(QtCore.QSize(100, 25))
        self.cbbLanguages.setMaximumSize(QtCore.QSize(150, 25))
        self.horizontalLayout_4.addWidget(self.cbbLanguages)
        self.label_cbbFontSetting = QtWidgets.QLabel(self.centralwidget)
        self.label_cbbFontSetting.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_cbbFontSetting)
        self.cbbFontSetting = QComboBox(self.centralwidget)
        self.cbbFontSetting.setObjectName("cbbFontSetting")
        self.cbbFontSetting.setMinimumSize(QtCore.QSize(100, 25))
        self.cbbFontSetting.setMaximumSize(QtCore.QSize(150, 25))
        self.horizontalLayout_4.addWidget(self.cbbFontSetting)
        self.label_cbbFontSetting_tolearn = QtWidgets.QLabel(self.centralwidget)
        self.label_cbbFontSetting_tolearn.setObjectName("label_cbbFontSetting_tolearn")
        self.horizontalLayout_4.addWidget(self.label_cbbFontSetting_tolearn)
        self.cbbFontSetting_tolearn = QComboBox(self.centralwidget)
        self.cbbFontSetting_tolearn.setObjectName("cbbFontSetting_tolearn")
        self.cbbFontSetting_tolearn.setMinimumSize(QtCore.QSize(100, 25))
        self.cbbFontSetting_tolearn.setMaximumSize(QtCore.QSize(150, 25))
        self.horizontalLayout_4.addWidget(self.cbbFontSetting_tolearn)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.slbVolume = QtWidgets.QSlider(self.centralwidget)
        self.slbVolume.setOrientation(QtCore.Qt.Horizontal)
        self.slbVolume.setObjectName("slbVolume")
        self.horizontalLayout_4.addWidget(self.slbVolume)
        self.txtVolume = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVolume.setMinimumSize(QtCore.QSize(55, 25))
        self.txtVolume.setMaximumSize(QtCore.QSize(55, 25))
        #self.txtVolume.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtVolume.setObjectName("txtVolume")
        self.horizontalLayout_4.addWidget(self.txtVolume)
        self.lbLastTest = QtWidgets.QLabel(self.centralwidget)
        self.lbLastTest.setMinimumSize(QtCore.QSize(270, 25))
        self.lbLastTest.setMaximumSize(QtCore.QSize(500, 25))
        self.lbLastTest.setObjectName("lbLastTest")
        self.horizontalLayout_4.addWidget(self.lbLastTest)
        self.btnPrintWords = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrintWords.setMinimumSize(QtCore.QSize(100, 25))
        self.btnPrintWords.setMaximumSize(QtCore.QSize(200, 25))
        self.btnPrintWords.setObjectName("btnPrintWords")
        self.horizontalLayout_4.addWidget(self.btnPrintWords)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "외저씨-단어테스트기3"))
        self.label.setText(_translate("MainWindow", "문제"))
        self.label_2.setText(_translate("MainWindow", "답"))
        self.btnDeleteAudios.setToolTip(_translate("MainWindow", "mp3폴더에 있는 파일들을 삭제합니다."))
        self.btnDeleteAudios.setText(_translate("MainWindow", "전체음성파일 삭제"))
        self.btnDeleteNowAudio.setToolTip(_translate("MainWindow", "현재 선택된 mp3파일만 삭제합니다."))
        self.btnDeleteNowAudio.setText(_translate("MainWindow", "현재음성파일 삭제"))
        self.btnRecord.setToolTip(_translate("MainWindow", "녹음을 시작합니다. \n"
"장치를 선택하고 확인을 누르면 녹음이 바로 시작됩니다. \n"
"영상을 정지시켜두고 녹음준비를 하세요."))
        self.btnRecord.setText(_translate("MainWindow", "녹음"))
        self.btnMakeAudios.setToolTip(_translate("MainWindow", "단어장에 있는 모든 단어의 mp3 파일을 생성합니다. \n"
" 미리 해두시면 시험에서 진행이 원활해집니다."))
        self.btnMakeAudios.setText(_translate("MainWindow", "음성파일 만들기"))
        self.btnOpenThisWordsMP3.setText(_translate("MainWindow", "지금단어 mp3열기"))
        self.btnOpenThisWordsMP3.setToolTip(_translate("MainWindow", "지금 선택된 단어의 MP3파일을 불러옵니다. \n 헷갈리는 부분을 반복청취해보세요."))
        self.btnAutoPlay.setToolTip(_translate("MainWindow", "표의 단어들을 자동으로 재생합니다. \n"
" 흘려듣기를 하고 싶다면 실행하세요."))
        self.btnAutoPlay.setText(_translate("MainWindow", "자동재생"))
        self.cbbPlayType.setToolTip(_translate("MainWindow", "자동재생 방식을 지정하세요."))
        self.chbToReadMeaning.setToolTip(_translate("MainWindow", "자동재생시 뜻도 같이 읽습니다."))
        self.chbToReadMeaning.setText(_translate("MainWindow", "뜻도 읽기"))
        self.label_13.setText(_translate("MainWindow", "텀:"))
        self.txtAutoAudioDuration.setToolTip(_translate("MainWindow", "자동재생의 텀을 지정하세요. \n"
"숫자만 쓰세요."))
        self.label_14.setText(_translate("MainWindow", "초"))
        self.label_3.setText(_translate("MainWindow", "피치 조절"))
        self.txtPitchControler.setToolTip(_translate("MainWindow", "피치를 낮게 조절하면 목소리가 두꺼워지고 높게 조절하면 얇아집니다."))
        self.label_4.setText(_translate("MainWindow", "속도 조절"))
        self.txtSpeedControler.setToolTip(_translate("MainWindow", "속도를 조절하여 발음을 천천히 들어보거나 음성 시험의 난이도를 높여보세요."))
        self.cbbPitchPreset.setToolTip(_translate("MainWindow", "피치와 속도값을 지정합니다."))
        self.cbbLangToLearn.setToolTip(_translate("MainWindow", "배우고싶은 언어를 지정하세요."))
        self.cbbLanguages.setToolTip(_translate("MainWindow", "Change to your language."))
        self.btnTextTestWtoM.setToolTip(_translate("MainWindow", "텍스트 시험을 봅니다. \n"
"단어를 보고 뜻을 쓰세요."))
        self.btnTextTestWtoM.setText(_translate("MainWindow", "시험"))
        self.label_5.setText(_translate("MainWindow", "시험순서"))
        self.btnEdit.setToolTip(_translate("MainWindow", "단어파일을 편집합니다. \n"
"단어를 추가하거나 제거하세요."))
        self.btnEdit.setText(_translate("MainWindow", "편집"))
        self.label_7.setText(_translate("MainWindow", "기본언어"))
        self.btnAudioTestWtoM.setToolTip(_translate("MainWindow", "음성 시험을 봅니다. \n"
"단어를 듣고 뜻을 쓰세요."))
        self.btnAudioTestWtoM.setText(_translate("MainWindow", "음성시험"))
        self.label_6.setText(_translate("MainWindow", "학습언어"))
        self.cbbTestType.setToolTip(_translate("MainWindow", "시험 순서를 지정해보세요. \n"
" 표 기준으로 위로 또는 아래로 또는 무작위로 시험을 진행하세요."))
        self.btnAudioTestMtoW.setToolTip(_translate("MainWindow", "음성 시험을 봅니다.\n"
" 뜻을 듣고 단어 원어를 쓰세요."))
        self.btnAudioTestMtoW.setText(_translate("MainWindow", "거꾸로음성"))
        self.cbbBaseLang.setToolTip(_translate("MainWindow", "모국어 또는 제2 사용언어를 선택하세요."))
        self.btnPractice.setToolTip(_translate("MainWindow", "연습모드는 표가 사라지지 않는 오픈북형식의 연습입니다. \n"
" 연습모드의 정답/오답은 정답률에 반영되지 않습니다."))
        self.btnPractice.setText(_translate("MainWindow", "연습"))
        self.btnAudioTestDictation.setToolTip(_translate("MainWindow", "음성 시험을 봅니다.\n"
"원어를 듣고 원어를 쓰세요."))
        self.btnAudioTestDictation.setText(_translate("MainWindow", "받아쓰기"))
        self.btnTextTestMtoW.setToolTip(_translate("MainWindow", "텍스트 시험을 봅니다. \n"
"뜻을 보고 원어를 쓰세요."))
        self.btnTextTestMtoW.setText(_translate("MainWindow", "거꾸로시험"))
        self.btn_browser.setToolTip(_translate("MainWindow", "현재 선택된 단어로 구글 검색을 해보세요. \n"
" 검색창이 열립니다. \n"
"(단축키 F10)"))
        self.btn_browser.setText(_translate("MainWindow", "현재 단어 검색"))
        self.btnDeleteScores.setToolTip(_translate("MainWindow", "번호, 단어, 뜻을 제외한 시험 결과를 전부 삭제합니다."))
        self.btnDeleteScores.setText(_translate("MainWindow", "기록삭제"))
        self.btnAlignCellsWidth.setToolTip(_translate("MainWindow", "표 넓이를 자동으로 정렬합니다."))
        self.btnAlignCellsWidth.setText(_translate("MainWindow", "표너비정렬"))
        self.btnAutoInputNumbers.setToolTip(_translate("MainWindow", "번호를 한 번에 입력합니다."))
        self.btnAutoInputNumbers.setText(_translate("MainWindow", "번호자동입력"))
        self.label_8.setText(_translate("MainWindow", "단어 파일"))
        self.cbbWordFile.setToolTip(_translate("MainWindow", "단어파일을 고를 수 있습니다. \n"
"휠로 빠르게 선택해보세요. \n파일을 다시 선택하려면 맨 위로 돌아가기를 누르세요."))
        self.btnWordFileOpen.setText(_translate("MainWindow", "단어파일열기"))
        self.btnWordFileOpen.setToolTip(_translate("MainWindow", "단어파일을 불러옵니다."))
        self.btnRefreshWordList.setToolTip(_translate("MainWindow", "새로 추가한 파일이 있다면 이 버튼을 눌러서 파일을 목록에 추가하세요."))
        self.btnRefreshWordList.setText(_translate("MainWindow", "목록새로고침"))
        self.btnDeleteWordFile.setToolTip(_translate("MainWindow", "현재 선택중인 파일을 삭제합니다. 될 수 있으면 삭제하지 말고 보관해서 나중에 또 시험을 진행해보세요."))
        self.btnDeleteWordFile.setText(_translate("MainWindow", "단어파일삭제"))
        self.btnMergeFiles.setToolTip(_translate("MainWindow", "여러 단어파일을 하나의 파일로 통합합니다."))
        self.btnMergeFiles.setText(_translate("MainWindow", "파일통합"))
        self.btnDivideFile.setToolTip(_translate("MainWindow", "단어를 분리하여 다른 파일로 저장합니다.\n단어를 복수 선택하고 버튼을 누르세요."))
        self.btnDivideFile.setText(_translate("MainWindow", "단어분리"))
        self.label_9.setText(_translate("MainWindow", "시험모드"))
        self.chbAllWords.setToolTip(_translate("MainWindow", "시험 시 모든 단어를 테스트합니다."))
        self.chbAllWords.setText(_translate("MainWindow", "모든 단어"))
        self.chbOnlyIncorrects.setToolTip(_translate("MainWindow", "시험 시 이전 시험의 오답문제만을 테스트 합니다."))
        self.chbOnlyIncorrects.setText(_translate("MainWindow", "오답만"))
        self.chbOnlyLowRates.setToolTip(_translate("MainWindow", "시험 시 지정한 정답률 이하의 단어만 시험을 봅니다."))
        self.chbOnlyLowRates.setText(_translate("MainWindow", "정답률"))
        self.label_10.setText(_translate("MainWindow", "이하만"))
        item = self.tbWordList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "번호"))
        item = self.tbWordList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "단어"))
        item = self.tbWordList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "뜻"))
        item = self.tbWordList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "오답비교"))
        item = self.tbWordList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "정답횟수"))
        item = self.tbWordList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "정답률"))
        item = self.tbWordList.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "최근소요시간"))
        item = self.tbWordList.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "최단소요시간"))
        item = self.tbWordList.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "방금시험채점"))
        item = self.tbWordList.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "마지막시험일시"))
        self.lbWordsCounter.setText(_translate("MainWindow", "남은 갯수: N/N"))
        self.lbTimer.setText(_translate("MainWindow", "00:00:00.000"))
        self.lbThreeCount.setText(_translate("MainWindow", "Count"))
        self.label_11.setText(_translate("MainWindow", "컬러테마:"))
        self.label_cbbLanguages.setText(_translate("MainWindow", "Languages:"))
        self.label_cbbFontSetting.setText(_translate("MainWindow", "글씨체:"))
        self.label_cbbFontSetting_tolearn.setText(_translate("MainWindow", "글씨체_학습언어:"))
        self.label_12.setText(_translate("MainWindow", "볼륨:"))
        self.txtVolume.setToolTip(_translate("MainWindow", "볼륨값을 입력하세요."))
        self.lbLastTest.setText(_translate("MainWindow", "마지막시험 n일 지남"))
        self.btnPrintWords.setToolTip(_translate("MainWindow", "표의 단어와 뜻을 출력합니다. \n"
"밖에서도 단어를 확인할 수 있습니다."))
        self.cbbTheme.setToolTip(_translate("MainWindow", "지루할 때 테마를 바꿔 집중력을 올려보세요."))
        self.btnPrintWords.setText(_translate("MainWindow", "단어출력"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
